BONDS = [
    {
        "id": "beignet",
        "name": "Project Beignet",
        "cusip": "076912AA2",
        "underlying_tenant_cusip": "30303M8X3",
        "location_display": "Richland Parish, LA",
        "location_city": "Rayville",
        "location_state": "Louisiana",
        "location_state_abbr": "LA",
        "lat": 32.4827,
        "lon": -91.7540,
        "news_queries": ["Richland Parish Louisiana datacenter", "Meta datacenter Louisiana", "Project Beignet datacenter"],
        "twitter_queries": ["Richland Parish datacenter", "Meta Louisiana datacenter"],
        # Financial
        "tranche_size_mm": 27294,
        "coupon": "6.581% (T+225)",
        "maturity": "2049 (~24yr)",
        "wal_yr": 17,
        "ratings": "NR/A+",
        "price": 102.376,
        "ytw_pct": 6.382,
        "stw_bps": 190.72,
        "ytc_pct": 6.382,
        "stc_bps": 190.72,
        "call_protection": "NCL",
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": 101.47,
        "spread_to_underlying_bps": 60.34,
        # Lease
        "lease_counterparty": "Meta",
        "counterparty_rating": "Aa3/AA/AA",
        "lease_tenor_yr": 24,
        "ultimate_tenant": "Meta",
        "ultimate_tenant_tenor_yr": 24,
        "guarantor": "Meta / Parent",
        "guarantee_trigger": "RVG since Inception",
        # Contingencies
        "power_contingency": "Perform under Entergy contract",
        "cost_overrun": "Pass through to Meta Parent",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 2100,
        "critical_it_mw": 1704,
        "critical_it_pct": 81,
        "pue": 1.232,
        "completion_date": "2029-06-01",
        # Economics
        "lease_agreement_mm": 28800,
        "contract_tenure_yr": 24,
        "initial_per_mw_yr_mm": 1.6,
        "construction_cost_mm": 28800,
        "per_mw_critical_mm": 16.9,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 9.47,
        "annual_revenue_mm": 2760,
        "noi_mm": 2760,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.11,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort through 2049",
        "amort_pct_tranche": "Full amort",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "Optional at par + make-whole",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "9.9x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Not Disclosed",
        "epc_market_cap": "N/A",
        "subcontractors": "N/A",
        "surety": "Meta Parent Gty (overruns >105%)",
    },
    {
        "id": "related_bx",
        "name": "Related/BX",
        "cusip": "74941YAA0",
        "underlying_tenant_cusip": "68389XDZ5",
        "location_display": "Washtenaw Co., MI",
        "location_city": "Ann Arbor",
        "location_state": "Michigan",
        "location_state_abbr": "MI",
        "lat": 42.2808,
        "lon": -83.7430,
        "news_queries": ["Washtenaw County Michigan datacenter", "Related Companies Oracle datacenter Michigan", "Ann Arbor datacenter"],
        "twitter_queries": ["Washtenaw Michigan datacenter", "Related BX Oracle datacenter"],
        "sub_tranches": [
            {
                "id": "related_bx_sd",
                "name": "Related/BX — Short-Duration Bond",
                "cusip": None,
                "underlying_tenant_cusip": "68389XDX0",
                "tranche_size_mm": 13849,
                "coupon": "6.250%",
                "maturity": "~6yr",
                "wal_yr": 6,
                "ratings": "NR/BBB/BBB-",
                "price": 99.0,
                "ytw_pct": 6.45,
                "stw_bps": 270.46,
                "ytc_pct": 7.59,
                "stc_bps": 409.40,
                "call_protection": 3,
                "call_price": 103.125,
                "ecf_sweep": "Cash Sweep",
                "ecf_sweep_annual": "N/A",
                "debt_noi_yr1": "10.0x",
                "debt_noi_maturity": "TBD",
                "amort_pct_tranche": "Full amort in lease",
                "amort_yr1": "I/O during term",
                "pct_principal_at_maturity": "N/A",
            },
            {
                "id": "related_bx_bank",
                "name": "Related/BX — Bank Financing",
                "cusip": None,
                "underlying_tenant_cusip": "68389XDZ5",
                "tranche_size_mm": 13849,
                "coupon": "S+300",
                "maturity": "4+1+1",
                "wal_yr": 4,
                "ratings": "NR/BBB/BBB-",
                "price": 100.0,
                "ytw_pct": None,
                "stw_bps": None,
                "ecf_sweep": "Cash Sweep",
                "ecf_sweep_annual": "Sculpted",
                "amort_pct_tranche": "Full amort in lease",
                "amort_yr1": "I/O during term",
            },
        ],
        # Financial (main tranche)
        "tranche_size_mm": 14000,
        "coupon": "7.500%",
        "maturity": "3/30/2045",
        "wal_yr": 14.25,
        "ratings": "NR/BBB/BBB-",
        "price": 100.102,
        "ytw_pct": 7.523,
        "stw_bps": 342.58,
        "ytc_pct": 7.454,
        "stc_bps": 370.40,
        "call_protection": 3,
        "call_price": 100.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": 189.5,
        "spread_to_underlying_bps": 164.49,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Related",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 1400,
        "critical_it_mw": 974,
        "critical_it_pct": 70,
        "pue": 1.22,
        "completion_date": "2028-03-31",
        # Economics
        "lease_agreement_mm": 16293,
        "contract_tenure_yr": 19.5,
        "initial_per_mw_yr_mm": 1.4,
        "construction_cost_mm": 16293,
        "per_mw_critical_mm": 16.7,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.75,
        "annual_revenue_mm": 1383,
        "noi_mm": 1383,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 9.88,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort in lease",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during term",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "10.0x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Walbridge (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "kW Mission Critical / SMC",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "vantage",
        "name": "Vantage",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Shackelford Co., TX + WI",
        "location_city": "Albany",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.7295,
        "lon": -99.2978,
        "news_queries": ["Shackelford County Texas datacenter Vantage", "Vantage Data Centers Oracle Texas", "Albany Texas datacenter"],
        "twitter_queries": ["Vantage datacenter Texas", "Vantage Data Centers Oracle"],
        # Financial
        "tranche_size_mm": 38000,
        "coupon": "S+250",
        "maturity": "4+1+1",
        "wal_yr": None,
        "ratings": "BBB (KBRA)",
        "price": 98,
        "ytw_pct": 7.5,
        "stw_bps": 345.28,
        "ytc_pct": 7.5,
        "stc_bps": 345.28,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Vantage",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 2260,
        "critical_it_mw": 2260,
        "critical_it_pct": 100,
        "pue": 1.22,
        "completion_date": "2028-09-01",
        # Economics
        "lease_agreement_mm": 44706,
        "contract_tenure_yr": 15.7,
        "initial_per_mw_yr_mm": 1.7,
        "construction_cost_mm": 44706,
        "per_mw_critical_mm": 19.8,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.5,
        "annual_revenue_mm": 3800,
        "noi_mm": 3800,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.0,
        "pct_principal_at_maturity": "98% (w/ extensions)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "100% Post-Maturity / 1.75yr pre-lease exp",
        "debt_noi_yr1": "10.0x",
        "debt_noi_maturity": "10.0x",
        # Construction
        "epc": "Kiewit (TX) / Turner, Whiting-Turner, Weitz, McCarthy (WI)",
        "epc_market_cap": "Private",
        "subcontractors": "Various Subs",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "stack_nm",
        "name": "Stack NM",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Santa Teresa, NM",
        "location_city": "Santa Teresa",
        "location_state": "New Mexico",
        "location_state_abbr": "NM",
        "lat": 31.8690,
        "lon": -106.6940,
        "news_queries": ["Santa Teresa New Mexico datacenter", "Dona Ana County New Mexico datacenter Stack", "Stack Infrastructure New Mexico Oracle"],
        "twitter_queries": ["Santa Teresa NM datacenter", "Stack Infrastructure New Mexico datacenter"],
        # Financial
        "tranche_size_mm": 18009,
        "coupon": "S+250",
        "maturity": "4+1+1",
        "wal_yr": None,
        "ratings": "BBB (KBRA)",
        "price": 96,
        "ytw_pct": 7.85,
        "stw_bps": 380.28,
        "ytc_pct": 9.25,
        "stc_bps": 520.28,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Stack",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 1725,
        "critical_it_mw": 1278,
        "critical_it_pct": 74,
        "pue": 1.35,
        "completion_date": "2028-08-31",
        # Economics
        "lease_agreement_mm": 21187,
        "contract_tenure_yr": 17.9,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 21187,
        "per_mw_critical_mm": 16.6,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.5,
        "annual_revenue_mm": 1857,
        "noi_mm": 1857,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.31,
        "pct_principal_at_maturity": "98% (w/ extensions)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "Sculpted",
        "debt_noi_yr1": "9.7x",
        "debt_noi_maturity": "9.7x",
        # Construction
        "epc": "Clayco-Kiewit JV (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "SMC (MEP Engineer)",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "tract",
        "name": "Tract",
        "cusip": "78488XAA2",
        "underlying_tenant_cusip": None,
        "location_display": "Storey County, NV",
        "location_city": "Virginia City",
        "location_state": "Nevada",
        "location_state_abbr": "NV",
        "lat": 39.3963,
        "lon": -119.6500,
        "news_queries": ["Storey County Nevada datacenter NVIDIA", "Tract NVIDIA datacenter Nevada", "Virginia City Nevada datacenter"],
        "twitter_queries": ["Storey County Nevada datacenter", "NVIDIA datacenter Nevada Tract"],
        # Financial
        "tranche_size_mm": 3800,
        "coupon": "5.875%",
        "maturity": "3/1/2031",
        "wal_yr": None,
        "ratings": "Ba1/BB",
        "price": 98.831,
        "ytw_pct": 6.158,
        "stw_bps": 199.69,
        "ytc_pct": 8.161,
        "stc_bps": 441.09,
        "call_protection": 2,
        "call_price": 102.938,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "NVIDIA",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 16,
        "ultimate_tenant": "NVIDIA",
        "ultimate_tenant_tenor_yr": 16,
        "guarantor": "Fleet",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "2031",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 200,
        "critical_it_mw": 200,
        "critical_it_pct": 100,
        "pue": None,
        "completion_date": "2029-08-15",
        # Economics
        "lease_agreement_mm": 7989,
        "contract_tenure_yr": 16.4,
        "initial_per_mw_yr_mm": 1.85,
        "construction_cost_mm": 4400,
        "per_mw_critical_mm": 22.0,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 9.5,
        "annual_revenue_mm": 370,
        "noi_mm": 370,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 9.74,
        "pct_principal_at_maturity": "93.1%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "3%",
        "amort_yr1": "$109mm",
        "amort_as_pct_noi": "29%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "9.9x",
        "debt_noi_maturity": "7.8x",
        # Construction
        "epc": "Clark Construction Group (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "Phase X / PASE (Private)",
        "surety": "Fleet I Completion Gty (GMP + Perf Bond TBD)",
    },
    {
        "id": "cifr_black_pearl",
        "name": "CIFR — Black Pearl",
        "cusip": "09216NAA8",
        "underlying_tenant_cusip": None,
        "location_display": "Wink, TX",
        "location_city": "Wink",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 31.7513,
        "lon": -103.1588,
        "news_queries": ["Wink Texas CIFR datacenter Amazon", "Cipher Mining Black Pearl datacenter", "Winkler County Texas datacenter"],
        "twitter_queries": ["Wink Texas CIFR datacenter", "Cipher Mining Amazon datacenter Texas"],
        # Financial
        "tranche_size_mm": 2000,
        "coupon": "6.125%",
        "maturity": "2/15/2031",
        "wal_yr": None,
        "ratings": "Ba2/—",
        "price": 101.386,
        "ytw_pct": 5.7,
        "stw_bps": 157.01,
        "ytc_pct": 6.969,
        "stc_bps": 321.91,
        "call_protection": 2,
        "call_price": 103.063,
        "market_cap": "$7.19B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Amazon",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Amazon",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "CIFR Parent ($6B mkt cap)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "150 days",
        "counterparty_debt_yield_pct": 4.27,
        "issuer_spread_to_cp_bps": 223.0,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 300,
        "critical_it_mw": 216,
        "critical_it_pct": 72,
        "pue": 1.4,
        "completion_date": "2027-01-28",
        # Economics
        "lease_agreement_mm": 5480,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.4,
        "construction_cost_mm": 2050,
        "per_mw_critical_mm": 9.5,
        "at_cost_to_debt": "1.0x",
        "yield_on_cost_pct": 14.74,
        "annual_revenue_mm": 300,
        "noi_mm": 298,
        "noi_margin_pct": 99,
        "implied_debt_yield_pct": 14.9,
        "pct_principal_at_maturity": "72.5%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "7%",
        "amort_yr1": "$140mm",
        "amort_as_pct_noi": "47%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "6.7x",
        "debt_noi_maturity": "3.x",
        # Construction
        "epc": "Quanta Services",
        "epc_market_cap": "$71.8B",
        "subcontractors": "Undisclosed",
        "surety": "$2,052mm parent gty",
    },
    {
        "id": "wulf",
        "name": "WULF",
        "cusip": "982911AA7",
        "underlying_tenant_cusip": None,
        "location_display": "Lake Mariner, NY",
        "location_city": "Somerset",
        "location_state": "New York",
        "location_state_abbr": "NY",
        "lat": 43.3445,
        "lon": -78.5076,
        "news_queries": ["Lake Mariner TeraWulf datacenter Google", "TeraWulf New York datacenter Fluidstack", "Somerset Niagara County New York datacenter"],
        "twitter_queries": ["TeraWulf Lake Mariner datacenter", "WULF Google datacenter New York"],
        # Financial
        "tranche_size_mm": 3200,
        "coupon": "7.750%",
        "maturity": "10/15/2030",
        "wal_yr": None,
        "ratings": "Ba2/BB",
        "price": 105.129,
        "ytw_pct": 6.037,
        "stw_bps": 192.18,
        "ytc_pct": 6.511,
        "stc_bps": 276.08,
        "call_protection": 2,
        "call_price": 103.875,
        "market_cap": "$8.25B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 10,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Terawulf Parent ($6B mkt cap)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "N/A",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 224.7,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 522.5,
        "critical_it_mw": 426,
        "critical_it_pct": 82,
        "pue": 1.2,
        "completion_date": "2026-12-26",
        # Economics
        "lease_agreement_mm": 6714,
        "contract_tenure_yr": 10,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 3659,
        "per_mw_critical_mm": 8.6,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 17.44,
        "annual_revenue_mm": 653,
        "noi_mm": 565,
        "noi_margin_pct": 87,
        "implied_debt_yield_pct": 17.66,
        "pct_principal_at_maturity": "60.1%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "8.78%",
        "amort_yr1": "$281mm",
        "amort_as_pct_noi": "50%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$60mm+",
        "debt_noi_yr1": "5.0x",
        "debt_noi_maturity": "2.6x",
        # Construction
        "epc": "Beowulf (Self Managed)",
        "epc_market_cap": "Various Small",
        "subcontractors": "Various Small",
        "surety": "$3,157mm parent gty",
    },
    {
        "id": "flashc",
        "name": "FLASHC",
        "cusip": "33853QAA9",
        "underlying_tenant_cusip": None,
        "location_display": "Abernathy, TX",
        "location_city": "Abernathy",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 33.8343,
        "lon": -101.8318,
        "news_queries": ["Abernathy Texas datacenter Fluidstack Google", "FLASHC datacenter Texas Hypertec", "Hale County Texas datacenter"],
        "twitter_queries": ["Abernathy Texas datacenter", "Fluidstack Google Texas datacenter FLASHC"],
        # Financial
        "tranche_size_mm": 1300,
        "coupon": "7.250%",
        "maturity": "12/31/2030",
        "wal_yr": None,
        "ratings": "Ba3/—",
        "price": 103.102,
        "ytw_pct": 6.264,
        "stw_bps": 213.97,
        "ytc_pct": 7.337,
        "stc_bps": 358.7,
        "call_protection": 2,
        "call_price": 103.625,
        "market_cap": "$8.25B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Fluidstack/TeraWulf JV $100mm",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "N/A (Life of lease)",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 315.2,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 240,
        "critical_it_mw": 168,
        "critical_it_pct": 70,
        "pue": 1.4,
        "completion_date": "2026-09-26",
        # Economics
        "lease_agreement_mm": 9500,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.331,
        "construction_cost_mm": 1354,
        "per_mw_critical_mm": 8.1,
        "at_cost_to_debt": "1.0x",
        "yield_on_cost_pct": 16.43,
        "annual_revenue_mm": 264,
        "noi_mm": 183,
        "noi_margin_pct": 69,
        "implied_debt_yield_pct": 14.08,
        "pct_principal_at_maturity": "65.0%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "5.77%",
        "amort_yr1": "$75mm",
        "amort_as_pct_noi": "41%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$16mm",
        "debt_noi_yr1": "7.0x",
        "debt_noi_maturity": "3.6x",
        # Construction
        "epc": "Hypertec (Private)",
        "epc_market_cap": "Mastec / Conti",
        "subcontractors": "Mastec / Conti",
        "surety": "$1,200mm Hypertec",
    },
    {
        "id": "cifr_barber_lake",
        "name": "CIFR (Barber Lake)",
        "cusip": "17253NAA5",
        "underlying_tenant_cusip": None,
        "location_display": "Colorado City, TX",
        "location_city": "Colorado City",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.3893,
        "lon": -100.8773,
        "news_queries": ["Colorado City Texas CIFR datacenter Google", "Mitchell County Texas datacenter Cipher Mining", "Colorado City Texas Barber Lake datacenter"],
        "twitter_queries": ["Colorado City Texas CIFR datacenter", "Cipher Mining Barber Lake Google"],
        # Financial
        "tranche_size_mm": 1733,
        "coupon": "7.125%",
        "maturity": "11/15/2030",
        "wal_yr": None,
        "ratings": "Ba3/—",
        "price": 103.995,
        "ytw_pct": 6.084,
        "stw_bps": 192.2,
        "ytc_pct": 6.569,
        "stc_bps": 281.88,
        "call_protection": 2,
        "call_price": 103.563,
        "market_cap": "$7.19B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 10,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "CIFR Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "180 days (Life of lease)",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 228.9,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 300,
        "critical_it_mw": 207,
        "critical_it_pct": 69,
        "pue": 1.4,
        "completion_date": "2026-09-30",
        # Economics
        "lease_agreement_mm": 3834,
        "contract_tenure_yr": 10,
        "initial_per_mw_yr_mm": 1.6,
        "construction_cost_mm": 1214,
        "per_mw_critical_mm": 10.7,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 14.95,
        "annual_revenue_mm": 333,
        "noi_mm": 288,
        "noi_margin_pct": 86,
        "implied_debt_yield_pct": 16.62,
        "pct_principal_at_maturity": "61.1%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "8.77%",
        "amort_yr1": "$152mm",
        "amort_as_pct_noi": "53%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$10mm+",
        "debt_noi_yr1": "5.5x",
        "debt_noi_maturity": "3.2x",
        # Construction
        "epc": "Quanta Services",
        "epc_market_cap": "$71.8B",
        "subcontractors": "Undisclosed",
        "surety": "$1,763mm parent gty",
    },
    {
        "id": "apld_pf2",
        "name": "APLD PF-2 (PFORGE)",
        "cusip": "03772CAA1",
        "underlying_tenant_cusip": "68389XDX0",
        "location_display": "Harwood, ND",
        "location_city": "Harwood",
        "location_state": "North Dakota",
        "location_state_abbr": "ND",
        "lat": 46.9757,
        "lon": -97.1845,
        "news_queries": ["Harwood North Dakota APLD datacenter Oracle", "Applied Digital Harwood ND datacenter", "Cass County North Dakota datacenter"],
        "twitter_queries": ["Harwood North Dakota datacenter", "APLD Applied Digital Oracle datacenter ND"],
        # Financial
        "tranche_size_mm": 2100,
        "coupon": "6.875%",
        "maturity": "3/15/2031",
        "wal_yr": None,
        "ratings": "BB",
        "price": 100.471,
        "ytw_pct": 6.604,
        "stw_bps": 244.9,
        "ytc_pct": 8.128,
        "stc_bps": 462.81,
        "call_protection": 2,
        "call_price": 103.44,
        "market_cap": "Private",
        "spread_for_underlying_bps": 144.91,
        "spread_to_underlying_bps": 108.04,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "TBD",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Applied Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "150 days",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 230,
        "critical_it_mw": 200,
        "critical_it_pct": 100,
        "pue": 1.15,
        "completion_date": "2027-04-01",
        # Economics
        "lease_agreement_mm": 9000,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.344,
        "construction_cost_mm": 2687,
        "per_mw_critical_mm": 13.4,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 10.03,
        "annual_revenue_mm": 250,
        "noi_mm": 250,
        "noi_margin_pct": 88,
        "implied_debt_yield_pct": 11.90,
        "pct_principal_at_maturity": "82.2%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "4.25%",
        "amort_yr1": "$61mm",
        "amort_as_pct_noi": "24.4%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "10.5x",
        "debt_noi_maturity": "6.7x",
        # Construction
        "epc": "Adolfson & Peterson (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "APLD Parent Completion Gty",
    },
    {
        "id": "apld",
        "name": "APLD",
        "cusip": "00202DAA5",
        "underlying_tenant_cusip": None,
        "location_display": "Ellendale, ND",
        "location_city": "Ellendale",
        "location_state": "North Dakota",
        "location_state_abbr": "ND",
        "lat": 46.0041,
        "lon": -98.5290,
        "news_queries": ["Ellendale North Dakota APLD datacenter CoreWeave", "Applied Digital Ellendale ND datacenter", "Dickey County North Dakota datacenter"],
        "twitter_queries": ["Ellendale North Dakota datacenter", "APLD Applied Digital CoreWeave datacenter"],
        # Financial
        "tranche_size_mm": 2350,
        "coupon": "9.250%",
        "maturity": "12/15/2030",
        "wal_yr": None,
        "ratings": "/BB-",
        "price": 107.903,
        "ytw_pct": 6.647,
        "stw_bps": 271.22,
        "ytc_pct": 6.647,
        "stc_bps": 289.75,
        "call_protection": 2,
        "call_price": 104.625,
        "market_cap": "$9.92B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "META",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Applied Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "180 days",
        "counterparty_debt_yield_pct": 9.70,
        "issuer_spread_to_cp_bps": -163.7,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 295,
        "critical_it_mw": 250,
        "critical_it_pct": 85,
        "pue": 1.2,
        "completion_date": "2026-06-26",
        # Economics
        "lease_agreement_mm": 6764,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 3100,
        "per_mw_critical_mm": 12.4,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 12.10,
        "annual_revenue_mm": 368,
        "noi_mm": 330,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 14.04,
        "pct_principal_at_maturity": "74.6%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "7.74%",
        "amort_yr1": "$182mm",
        "amort_as_pct_noi": "55%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$60mm",
        "debt_noi_yr1": "6.6x",
        "debt_noi_maturity": "~0x (near full amort)",
        # Construction
        "epc": "McGough (Private)",
        "epc_market_cap": "Undisclosed",
        "subcontractors": "Undisclosed",
        "surety": "$3,099mm parent gty",
    },
    {
        "id": "voltag",
        "name": "VOLTAG",
        "cusip": "92874BAA3",
        "underlying_tenant_cusip": None,
        "location_display": "Shackelford Co., TX",
        "location_city": "Albany",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.7295,
        "lon": -99.2978,
        "news_queries": ["Shackelford County Texas VOLTAG datacenter Oracle Vantage", "Vantage Data Centers Oracle Texas Albany", "Albany Texas datacenter Shackelford"],
        "twitter_queries": ["Shackelford Texas VOLTAG datacenter", "Vantage Oracle Texas datacenter"],
        # Financial
        "tranche_size_mm": 2000,
        "coupon": "7.375%",
        "maturity": "11/1/2030",
        "wal_yr": None,
        "ratings": "B3/B+/BB-",
        "price": 103.827,
        "ytw_pct": 6.156,
        "stw_bps": 233.02,
        "ytc_pct": 7.017,
        "stc_bps": 356.66,
        "call_protection": 2,
        "call_price": 103.688,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": None,
        "ultimate_tenant": "OpenAI",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "ORCL (Vantage)",
        "guarantee_trigger": None,
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": None,
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": None,
        "critical_it_mw": None,
        "critical_it_pct": None,
        "pue": None,
        "completion_date": None,
        # Economics
        "lease_agreement_mm": None,
        "contract_tenure_yr": None,
        "initial_per_mw_yr_mm": None,
        "construction_cost_mm": None,
        "per_mw_critical_mm": None,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": None,
        "annual_revenue_mm": None,
        "noi_mm": None,
        "noi_margin_pct": None,
        "implied_debt_yield_pct": None,
        "pct_principal_at_maturity": None,
        "amort_schedule": "Yes",
        "amort_pct_tranche": None,
        "amort_yr1": None,
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": None,
        "debt_noi_yr1": None,
        "debt_noi_maturity": None,
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "qts",
        "name": "QTS",
        "cusip": "74751AAA1",
        "underlying_tenant_cusip": "594918BS2",
        "location_display": "Fayetteville, GA",
        "location_city": "Fayetteville",
        "location_state": "Georgia",
        "location_state_abbr": "GA",
        "lat": 33.4490,
        "lon": -84.4549,
        "news_queries": ["Fayetteville Georgia QTS datacenter Microsoft", "QTS Realty Trust Microsoft Georgia datacenter", "Fayette County Georgia datacenter"],
        "twitter_queries": ["Fayetteville Georgia QTS datacenter", "QTS Microsoft datacenter Georgia"],
        # Financial
        "tranche_size_mm": 4600,
        "coupon": "7.375%",
        "maturity": "4/15/2036",
        "wal_yr": None,
        "ratings": "Baa2",
        "price": 96.803,
        "ytw_pct": 6.131,
        "stw_bps": 165.59,
        "ytc_pct": 6.131,
        "stc_bps": 165.59,
        "call_protection": 10,
        "call_price": 100.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "MSFT",
        "counterparty_rating": "Aaa/AAA",
        "lease_tenor_yr": 20,
        "ultimate_tenant": "MSFT",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "QTS",
        "guarantee_trigger": None,
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": None,
        "counterparty_debt_yield_pct": 4.5,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": None,
        "critical_it_mw": None,
        "critical_it_pct": None,
        "pue": None,
        "completion_date": None,
        # Economics
        "lease_agreement_mm": None,
        "contract_tenure_yr": None,
        "initial_per_mw_yr_mm": None,
        "construction_cost_mm": None,
        "per_mw_critical_mm": None,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": None,
        "annual_revenue_mm": None,
        "noi_mm": None,
        "noi_margin_pct": None,
        "implied_debt_yield_pct": None,
        "pct_principal_at_maturity": None,
        "amort_schedule": "Yes",
        "amort_pct_tranche": None,
        "amort_yr1": None,
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": None,
        "debt_noi_yr1": None,
        "debt_noi_maturity": None,
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
        # Separate bond under the QTS ticker: ATL2 DC6-7 (GS-led, ~2026 issue)
        "sub_tranches": [
            {
                "id": "qts_dc3_7",
                "name": "QTS — ATL2 DC6-7",
                "cusip": None,
                "underlying_tenant_cusip": "EJ653190",
                "tranche_size_mm": 5370,
                "coupon": "7.250%",
                "maturity": "2031 (~5yr)",
                "wal_yr": 5,
                "ratings": "Ba1/BB+",
                "price": 100.0,
                "ytw_pct": 7.500,
                "stw_bps": 303.8,
                "ytc_pct": 8.896,
                "stc_bps": 514.65,
                "call_protection": "Aug-2028",
                "call_price": 103.0,
                "ecf_sweep": "None",
                "ecf_sweep_annual": "Sculpted (1.00x DSCR)",
                "debt_noi_yr1": "9.0x",
                "debt_noi_maturity": "9.7x",
                "amort_pct_tranche": "Sculpted to 1.00x DSCR",
                "amort_yr1": "I/O during construction",
                "pct_principal_at_maturity": "~96%",
            },
        ],
    },
    {
        "id": "meridian",
        "name": "Meridian",
        "cusip": "58990CAA1",
        "underlying_tenant_cusip": "02079KBK2",
        "location_display": "Sullivan Co., IN",
        "location_city": "New Lebanon",
        "location_state": "Indiana",
        "location_state_abbr": "IN",
        "lat": 39.1667,
        "lon": -87.4167,
        "news_queries": ["New Lebanon Indiana datacenter Google", "Sullivan County Indiana datacenter", "Meridian datacenter Fluidstack Indiana", "Next Frontier Capital datacenter Indiana"],
        "twitter_queries": ["Sullivan County Indiana datacenter", "Meridian datacenter Google Indiana"],
        # Financial
        "tranche_size_mm": 5700,
        "coupon": "6.500%",
        "maturity": "4/30/2031",
        "wal_yr": None,
        "ratings": "Ba1/BB",
        "price": 100.319,
        "ytw_pct": 6.144,
        "stw_bps": 200.52,
        "ytc_pct": 7.598,
        "stc_bps": 384.77,
        "call_protection": 2,
        "call_price": 103.125,
        "market_cap": "Private",
        "spread_for_underlying_bps": 71.71,
        "spread_to_underlying_bps": 157.73,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Private/NR",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Fluidstack + Next Frontier ($100mm each)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 581,
        "critical_it_mw": 430,
        "critical_it_pct": 74,
        "pue": 1.35,
        "completion_date": "2028-02-28",
        # Economics
        "lease_agreement_mm": 12108,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.514,
        "construction_cost_mm": 6250,
        "per_mw_critical_mm": 14.5,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 10.42,
        "annual_revenue_mm": 651,
        "noi_mm": 651,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 11.42,
        "pct_principal_at_maturity": "84.1%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Sculpted to 1.25x DSCR",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "Sculpted (1.25x DSCR)",
        "debt_noi_yr1": "8.8x",
        "debt_noi_maturity": "7.4x",
        # Construction
        "epc": "ARCO DB Companies, Inc.",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "edged_compute",
        "name": "Edged Compute",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Aurora, IL + Atlanta, GA",
        "location_city": "Aurora",
        "location_state": "Illinois",
        "location_state_abbr": "IL",
        "lat": 41.7606,
        "lon": -88.3201,
        "news_queries": ["Aurora Illinois datacenter CoreWeave Edged", "Edged Compute datacenter CoreWeave Alibaba", "Edged Energy datacenter Illinois Atlanta", "Aurora Illinois datacenter Koch"],
        "twitter_queries": ["Edged Compute datacenter", "Aurora Illinois CoreWeave datacenter"],
        # Financial
        "tranche_size_mm": 1300,
        "coupon": "7.500%",
        "maturity": "4/30/2031",
        "wal_yr": 4.75,
        "ratings": "~BB",
        "price": 99.713,
        "ytw_pct": 7.577,
        "stw_bps": 342.17,
        "ytc_pct": 9.435,
        "stc_bps": 538.74,
        "call_protection": 2,
        "call_price": 103.75,
        "market_cap": "Private",
        "spread_for_underlying_bps": 608.86,
        "spread_to_underlying_bps": -250.41,
        # Lease
        "lease_counterparty": "CoreWeave / Alibaba",
        "counterparty_rating": "B1/B/BB- (CW) / NR (Alibaba)",
        "lease_tenor_yr": 16,
        "ultimate_tenant": "CoreWeave / Alibaba",
        "ultimate_tenant_tenor_yr": 16,
        "guarantor": "Edged US Parent (uncapped, Koch)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "NNN (Chicago) / Landlord (Atlanta)",
        "cost_overrun": "BABA: Landlord bears overruns; CRWV: rent adjusts for cost increases",
        "construction_delay": "270 days CRWV / None ATL",
        "counterparty_debt_yield_pct": 10.0,
        "issuer_spread_to_cp_bps": -250.41,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 142,
        "critical_it_mw": 114,
        "critical_it_pct": 80,
        "pue": 1.25,
        "completion_date": "2027-12-31",
        # Economics
        "lease_agreement_mm": 3590,
        "contract_tenure_yr": 16,
        "initial_per_mw_yr_mm": 1.737,
        "construction_cost_mm": 1721,
        "per_mw_critical_mm": 15.1,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 11.50,
        "annual_revenue_mm": 198,
        "noi_mm": 179,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 13.77,
        "pct_principal_at_maturity": "90%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "5.08%",
        "amort_yr1": "I/O",
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "7.3x",
        "debt_noi_maturity": "6.5x",
        # Construction
        "epc": "FCL Builders (Chicago) / Brasfield & Gorrie (Atlanta)",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "GMP w/ Parent Uncapped Gty",
    },
    {
        "id": "core_scientific",
        "name": "Core Scientific",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Multiple (TX/NC/OK/GA)",
        "location_city": "Denton",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 33.2148,
        "lon": -97.1331,
        "news_queries": ["Core Scientific CoreWeave HPC datacenter", "CORZ datacenter hosting AI", "Core Scientific datacenter lease CoreWeave"],
        "twitter_queries": ["Core Scientific CoreWeave datacenter", "CORZ HPC datacenter"],
        # Financial
        "tranche_size_mm": 3300,
        "coupon": "7.500%",
        "maturity": "4/30/2031",
        "wal_yr": 4.25,
        "ratings": "~BB",
        "price": 101.987,
        "ytw_pct": 7.146,
        "stw_bps": 300.92,
        "ytc_pct": 8.421,
        "stc_bps": 437.35,
        "call_protection": 2,
        "call_price": 103.75,
        "market_cap": "Public (CORZ)",
        "spread_for_underlying_bps": 608.86,
        "spread_to_underlying_bps": -250.46,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 12,
        "ultimate_tenant": "OAI / Meta / MSFT",
        "ultimate_tenant_tenor_yr": 12,
        "guarantor": "CoreWeave",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": "CoreWeave",
        "construction_delay": "None",
        "counterparty_debt_yield_pct": 10.0,
        "issuer_spread_to_cp_bps": -250.46,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 900,
        "critical_it_mw": 590,
        "critical_it_pct": 66,
        "pue": 1.53,
        "completion_date": "2027-06-30",
        # Economics
        "lease_agreement_mm": 9155,
        "contract_tenure_yr": 12,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 5500,
        "per_mw_critical_mm": 9.32,
        "at_cost_to_debt": "1.7x",
        "yield_on_cost_pct": 16.09,
        "annual_revenue_mm": 763,
        "noi_mm": 602,
        "noi_margin_pct": 79,
        "implied_debt_yield_pct": 18.24,
        "pct_principal_at_maturity": "73.8%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "11.5%",
        "amort_yr1": "$0",
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "5.5x",
        "debt_noi_maturity": "1.9x",
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "hut_google",
        "name": "HUT / Google",
        "cusip": None,
        "underlying_tenant_cusip": "02079KBK2",
        "location_display": "River Bend, LA",
        "location_city": "River Bend",
        "location_state": "Louisiana",
        "location_state_abbr": "LA",
        "lat": 30.7500,
        "lon": -91.3330,
        "news_queries": ["River Bend Louisiana HUT Google datacenter", "HUT 8 Google datacenter Louisiana", "St Francisville Louisiana datacenter"],
        "twitter_queries": ["River Bend Louisiana datacenter Google", "HUT Google datacenter Louisiana"],
        # Financial
        "tranche_size_mm": 3248,
        "coupon": "6.200%",
        "maturity": "12/31/2042",
        "wal_yr": 12,
        "ratings": "Baa2/BBB-",
        "price": 100.866,
        "ytw_pct": 6.071,
        "stw_bps": 159.57,
        "ytc_pct": 6.071,
        "stc_bps": 159.57,
        "call_protection": "NCL",
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": 36.5,
        "spread_to_underlying_bps": 140.19,
        # Lease
        "lease_counterparty": "Fluidstack / Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google/Anthropic",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Hut/Jacobs/Google",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "GMP with Jacobs",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 330,
        "critical_it_mw": 245,
        "critical_it_pct": 74,
        "pue": 1.347,
        "completion_date": "2027-10-01",
        # Economics
        "lease_agreement_mm": 6982,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.853,
        "construction_cost_mm": 3468,
        "per_mw_critical_mm": 14.16,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 13.09,
        "annual_revenue_mm": 454,
        "noi_mm": 454,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 13.98,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "7.2x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Jacobs",
        "epc_market_cap": "$15B",
        "subcontractors": "Vertiv",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "hut_beacon_point",
        "name": "HUT / Beacon Point",
        "cusip": None,
        "underlying_tenant_cusip": "BH393780",
        "location_display": "Nueces County, TX",
        "location_city": "Corpus Christi",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 27.8006,
        "lon": -97.3964,
        "news_queries": ["Nueces County Texas datacenter NVIDIA", "HUT Beacon Point datacenter Texas", "Corpus Christi Texas datacenter NVIDIA"],
        "twitter_queries": ["Nueces County Texas NVIDIA datacenter", "HUT Beacon Point datacenter"],
        # Financial
        "tranche_size_mm": 4275,
        "coupon": None,
        "maturity": "11/30/2042",
        "wal_yr": 11.56,
        "ratings": None,
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": "NCL",
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "NVIDIA",
        "counterparty_rating": "AA- or better",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "NVIDIA",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Hut / Jacobs",
        "guarantee_trigger": "RFS",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "GMP with Jacobs",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 500,
        "critical_it_mw": 352,
        "critical_it_pct": 70,
        "pue": 1.42,
        "completion_date": "2028-04-28",
        # Economics
        "lease_agreement_mm": 9788,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.39,
        "construction_cost_mm": 3871,
        "per_mw_critical_mm": 11.0,
        "at_cost_to_debt": "0.9x",
        "yield_on_cost_pct": 12.64,
        "annual_revenue_mm": 489,
        "noi_mm": 612,
        "noi_margin_pct": None,
        "implied_debt_yield_pct": 14.31,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort in lease",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "7.0x",
        "debt_noi_maturity": "6.5x",
        # Construction
        "epc": "Jacobs",
        "epc_market_cap": "$15B",
        "subcontractors": "Vertiv",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "tract_d",
        "name": "Tract — D",
        "cusip": "69393LAA1",
        "underlying_tenant_cusip": "67066GAN4",
        "location_display": "Storey County, NV",
        "location_city": "Virginia City",
        "location_state": "Nevada",
        "location_state_abbr": "NV",
        "lat": 39.3963,
        "lon": -119.6500,
        "news_queries": ["Storey County Nevada datacenter NVIDIA", "Tract NVIDIA datacenter Nevada", "Virginia City Nevada datacenter"],
        "twitter_queries": ["Storey County Nevada datacenter", "NVIDIA datacenter Nevada Tract"],
        # Financial
        "tranche_size_mm": 4539,
        "coupon": "6.500%",
        "maturity": "5/1/2031",
        "wal_yr": None,
        "ratings": "Ba1/BB",
        "price": 100.021,
        "ytw_pct": 6.481,
        "stw_bps": 230.37,
        "ytc_pct": 8.066,
        "stc_bps": 431.65,
        "call_protection": 2,
        "call_price": 103.25,
        "market_cap": "Private",
        "spread_for_underlying_bps": 18,
        "spread_to_underlying_bps": 212.37,
        # Lease
        "lease_counterparty": "NVIDIA",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 16,
        "ultimate_tenant": "NVIDIA",
        "ultimate_tenant_tenor_yr": 16,
        "guarantor": "Fleet",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "2031",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 200,
        "critical_it_mw": 200,
        "critical_it_pct": 100,
        "pue": None,
        "completion_date": "2028-04-30",
        # Economics
        "lease_agreement_mm": 9475,
        "contract_tenure_yr": 16,
        "initial_per_mw_yr_mm": 1.85,
        "construction_cost_mm": 4435,
        "per_mw_critical_mm": 22.2,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 9.5,
        "annual_revenue_mm": 425,
        "noi_mm": 425,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 9.36,
        "pct_principal_at_maturity": "95%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "2.5%",
        "amort_yr1": "$113mm",
        "amort_as_pct_noi": "27%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "9.7x",
        "debt_noi_maturity": "8.1x",
        # Construction
        "epc": "Clark Construction Group (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "Phase X / PASE (Private)",
        "surety": "$4,433mm Clark",
    },
    {
        "id": "polar_dc",
        "name": "PolarDC",
        "cusip": "NO0013752949",
        "underlying_tenant_cusip": "21873SAG3",
        "location_display": "Drangedal & Herøya, Norway",
        "location_city": "Drangedal",
        "location_state": "Norway",
        "location_state_abbr": "NO",
        "lat": 59.1106,
        "lon": 9.0545,
        "news_queries": ["Drangedal Norway PolarDC datacenter Crusoe CoreWeave", "Herøya Norway datacenter Crusoe CRWV", "Norway datacenter CRWV PolarDC"],
        "twitter_queries": ["PolarDC Norway datacenter", "Crusoe CoreWeave Norway datacenter"],
        # Financial
        "tranche_size_mm": 800,
        "coupon": "8.276%",
        "maturity": "6/4/2030",
        "wal_yr": 4,
        "ratings": "NR",
        "price": 102.08,
        "ytw_pct": 7.661,
        "stw_bps": None,
        "ytc_pct": 8.882,
        "stc_bps": None,
        "call_protection": 2,
        "call_price": 103.75,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Crusoe / CRWV",
        "counterparty_rating": "NR / B1/B/BB-",
        "lease_tenor_yr": None,
        "ultimate_tenant": "[MSFT] / [OAI]",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "1083 AS (Issuer)",
        "guarantee_trigger": "None",
        # Contingencies
        "power_contingency": "Pass-through",
        "cost_overrun": "Sponsor (limited)",
        "construction_delay": "180-210 days",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey / Powered Shell",
        "total_campus_mw": 112,
        "critical_it_mw": 93,
        "critical_it_pct": 83,
        "pue": 1.2,
        "completion_date": "Q4 2027",
        # Economics
        "lease_agreement_mm": 2081,
        "contract_tenure_yr": 10,
        "initial_per_mw_yr_mm": 1.633,
        "construction_cost_mm": 1193,
        "per_mw_critical_mm": 12.83,
        "at_cost_to_debt": "1.5x",
        "yield_on_cost_pct": 12.73,
        "annual_revenue_mm": 152,
        "noi_mm": 110,
        "noi_margin_pct": 73,
        "implied_debt_yield_pct": 13.76,
        "pct_principal_at_maturity": "100%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "0%",
        "amort_yr1": "$0mm",
        "amort_as_pct_noi": "0%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "7.3x",
        "debt_noi_maturity": "7.3x",
        # Construction
        "epc": "BRG + Jones Engineering",
        "epc_market_cap": None,
        "subcontractors": "Vertiv",
        "surety": None,
    },
    {
        "id": "prime_dc",
        "name": "Prime DC",
        "cusip": "BBG022QPT962",
        "underlying_tenant_cusip": "21873SAG3",
        "location_display": "Elk Grove Village, IL",
        "location_city": "Elk Grove Village",
        "location_state": "Illinois",
        "location_state_abbr": "IL",
        "lat": 41.9942,
        "lon": -87.9973,
        "news_queries": ["Elk Grove Village Illinois datacenter CoreWeave Prime DC", "Elk Grove Village Chicago datacenter CoreWeave", "Cook County Illinois datacenter Prime DC"],
        "twitter_queries": ["Elk Grove Village Illinois CoreWeave datacenter", "Prime DC Chicago datacenter CoreWeave"],
        # Financial
        "tranche_size_mm": 900,
        "coupon": "7.500%",
        "maturity": "6/15/2031",
        "wal_yr": 4.85,
        "ratings": "Ba3/BB-",
        "price": 101.199,
        "ytw_pct": 7.5,
        "stw_bps": 301.71,
        "ytc_pct": 8.352,
        "stc_bps": 430.52,
        "call_protection": 2.5,
        "call_price": 103.75,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Jane St + Enterprise",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Prime DC (Parent Completion Gty)",
        "guarantee_trigger": "RFS",
        # Contingencies
        "power_contingency": "Pass-through",
        "cost_overrun": "Parent",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": 8.91,
        "issuer_spread_to_cp_bps": -140.6,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 86,
        "critical_it_mw": 72,
        "critical_it_pct": 84,
        "pue": 1.19,
        "completion_date": "2027-01-01",
        # Economics
        "lease_agreement_mm": 1750,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.62,
        "construction_cost_mm": 945,
        "per_mw_critical_mm": 13.13,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 12.80,
        "annual_revenue_mm": 117,
        "noi_mm": 121,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 13.44,
        "pct_principal_at_maturity": "80%",
        "amort_schedule": "Semi-annual mandatory amort",
        "amort_pct_tranche": "4%",
        "amort_yr1": "$36mm",
        "amort_as_pct_noi": "30%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "7.4x",
        "debt_noi_maturity": "6.0x",
        # Construction
        "epc": "Clune Construction",
        "epc_market_cap": "Private",
        "subcontractors": "Gensler / Syska Hennessy",
        "surety": "GMP w/ Liquidated Damages",
    },
    {
        "id": "sbe_softbank",
        "name": "SBE / Softbank",
        "cusip": None,
        "underlying_tenant_cusip": "XS3112542272",
        "location_display": "Austin, TX",
        "location_city": "Austin",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 30.2672,
        "lon": -97.7431,
        "news_queries": ["Austin Texas SBE Softbank datacenter", "Softbank Austin Texas datacenter", "Travis County Texas datacenter Softbank"],
        "twitter_queries": ["Austin Texas Softbank datacenter", "SBE Softbank datacenter Texas"],
        # Financial
        "tranche_size_mm": 1000,
        "coupon": "8.000%",
        "maturity": "4/30/2031",
        "wal_yr": 4.75,
        "ratings": "~BB",
        "price": 103.72,
        "ytw_pct": 7.751,
        "stw_bps": 361.16,
        "ytc_pct": 8.568,
        "stc_bps": 452.06,
        "call_protection": 2,
        "call_price": 104.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": 400.0,
        "spread_to_underlying_bps": -8.71,
        # Lease
        "lease_counterparty": "Softbank",
        "counterparty_rating": "Ba2/BB+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Softbank",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Softbank",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": "Softbank",
        "construction_delay": "None",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 70,
        "critical_it_mw": 50,
        "critical_it_pct": 71,
        "pue": 1.4,
        "completion_date": "2027-06-30",
        # Economics
        "lease_agreement_mm": 2400,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 1181,
        "per_mw_critical_mm": 23.62,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 11.62,
        "annual_revenue_mm": 167,
        "noi_mm": 167,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 16.67,
        "pct_principal_at_maturity": "92.5%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "0%",
        "amort_yr1": "$0mm",
        "amort_as_pct_noi": "0%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "6.0x",
        "debt_noi_maturity": "5.5x",
        # Construction
        "epc": "Turner",
        "epc_market_cap": "Private",
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "cifr_stingray",
        "name": "CIFR — Stingray",
        "cusip": None,  # Bloomberg loan ID DL653512 (prices 6/15/2026)
        "underlying_tenant_cusip": "023135DD5",  # Amazon
        "location_display": "Andrews, TX",
        "location_city": "Andrews",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.3187,
        "lon": -102.5460,
        "news_queries": ["Andrews County Texas datacenter Amazon", "Cipher Mining Stingray datacenter Andrews Texas", "Andrews Texas AWS datacenter", "Permian Basin datacenter Andrews County"],
        "twitter_queries": ["Andrews County Texas datacenter", "Cipher Mining Amazon datacenter Texas"],
        # Financial
        "tranche_size_mm": 810,
        "coupon": "6.000%",
        "maturity": "6/15/2031",
        "wal_yr": None,
        "ratings": None,
        "price": 100.194,
        "ytw_pct": 5.943,
        "stw_bps": 181.77,
        "ytc_pct": 7.342,
        "stc_bps": 359.22,
        "call_protection": 2,
        "call_price": 103.0,
        "market_cap": "$7.19B",
        "spread_for_underlying_bps": 40.0,
        "spread_to_underlying_bps": 141.77,
        # Lease
        "lease_counterparty": "Amazon",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Amazon",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "CIFR Parent ($6B mkt cap)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": "Amazon covers overruns >$10.5mm/IT MW",
        "construction_delay": "180 days",
        "counterparty_debt_yield_pct": 4.54,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 100,
        "critical_it_mw": 70,
        "critical_it_pct": 70,
        "pue": 1.43,
        "completion_date": "2027-05-01",
        # Economics
        "lease_agreement_mm": 2033,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.6,
        "construction_cost_mm": 735,
        "per_mw_critical_mm": 10.5,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 15.24,
        "annual_revenue_mm": 135,
        "noi_mm": 135,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 16.67,
        "pct_principal_at_maturity": "71.0%",
        "amort_schedule": "Mandatory amort from completion at 1.25x DSCR",
        "amort_pct_tranche": "Sculpted to 1.25x DSCR",
        "amort_yr1": "$27mm",
        "amort_as_pct_noi": "20%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "6.0x",
        "debt_noi_maturity": "4.3x",
        # Construction
        "epc": "Quanta Services (Public $PWR)",
        "epc_market_cap": "$104B",
        "subcontractors": "Undisclosed",
        "surety": None,
    },
    {
        "id": "apld_eln4",
        "name": "APLD / ELN4",
        "cusip": None,  # Bloomberg loan ID DL702503 (prices 6/16/2026)
        "underlying_tenant_cusip": None,
        "location_display": "Ellendale, ND",
        "location_city": "Ellendale",
        "location_state": "North Dakota",
        "location_state_abbr": "ND",
        "lat": 46.0041,
        "lon": -98.5290,
        "news_queries": ["Ellendale North Dakota datacenter CoreWeave Meta", "Applied Digital Ellendale ND datacenter ELN4", "Dickey County North Dakota datacenter", "APLD Ellendale datacenter Meta"],
        "twitter_queries": ["Ellendale North Dakota datacenter", "APLD CoreWeave Meta datacenter ND"],
        # Financial
        "tranche_size_mm": 1590,
        "coupon": "7.000%",
        "maturity": "6/15/2031",
        "wal_yr": None,
        "ratings": "BB-",
        "price": 99.886,
        "ytw_pct": 7.031,
        "stw_bps": 290.29,
        "ytc_pct": 8.739,
        "stc_bps": 498.91,
        "call_protection": 2,
        "call_price": 103.5,
        "market_cap": "$9.92B",
        "spread_for_underlying_bps": 578.39,
        "spread_to_underlying_bps": -288.10,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Meta",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Applied Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": "Parent",
        "construction_delay": "180 days",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 180,
        "critical_it_mw": 150,
        "critical_it_pct": 83,
        "pue": 1.2,
        "completion_date": "2027-06-30",
        # Economics
        "lease_agreement_mm": 4100,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.82,
        "construction_cost_mm": 1083,
        "per_mw_critical_mm": 7.22,
        "at_cost_to_debt": "0.7x",
        "yield_on_cost_pct": 25.24,
        "annual_revenue_mm": 273,
        "noi_mm": 246,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 15.47,
        "pct_principal_at_maturity": "74.6%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "7.74%",
        "amort_yr1": "$182mm",
        "amort_as_pct_noi": "55%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "6.5x",
        "debt_noi_maturity": "4.8x",
        # Construction
        "epc": "McGough (Private)",
        "epc_market_cap": "Undisclosed",
        "subcontractors": "Undisclosed",
        "surety": None,
    },
    {
        "id": "yondr_nova",
        "name": "Yondr NoVa North",
        "cusip": "985925AA4",
        "underlying_tenant_cusip": "21873SAG3",
        "location_display": "Aldie, VA",
        "location_city": "Aldie",
        "location_state": "Virginia",
        "location_state_abbr": "VA",
        "lat": 38.9776,
        "lon": -77.6411,
        "news_queries": ["Yondr datacenter Aldie Loudoun County Virginia", "Yondr Northern Virginia Oracle datacenter", "Loudoun County datacenter Yondr Aldie", "Aldie Virginia hyperscale datacenter"],
        "twitter_queries": ["Yondr datacenter Loudoun Virginia", "Aldie Virginia datacenter Oracle"],
        # Financial
        "tranche_size_mm": 715,
        "coupon": "7.250%",
        "maturity": "6/15/2031",
        "wal_yr": None,
        "ratings": "Low BB",
        "price": 100.0,
        "ytw_pct": 7.25,
        "stw_bps": 310.58,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": 2,
        "call_price": 103.625,
        "market_cap": "Private",
        "spread_for_underlying_bps": 578.39,
        "spread_to_underlying_bps": -267.81,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "TBD",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Yondr Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": "Parent",
        "construction_delay": "12 months",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 67.2,
        "critical_it_mw": 48,
        "critical_it_pct": 71,
        "pue": 1.4,
        "completion_date": "2028-09-27",
        # Economics
        "lease_agreement_mm": 1425,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.98,
        "construction_cost_mm": 648,
        "per_mw_critical_mm": 13.5,
        "at_cost_to_debt": "0.9x",
        "yield_on_cost_pct": 12.65,
        "annual_revenue_mm": 95,
        "noi_mm": 82,
        "noi_margin_pct": 86,
        "implied_debt_yield_pct": 11.47,
        "pct_principal_at_maturity": "100%",
        "amort_schedule": "None",
        "amort_pct_tranche": "0%",
        "amort_yr1": "$0mm",
        "amort_as_pct_noi": "0%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "8.7x",
        "debt_noi_maturity": "8.7x",
        # Construction
        "epc": "HITT + Bowman",
        "epc_market_cap": "Private",
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "sopaipilla",
        "name": "Sopaipilla",
        "cusip": None,
        "underlying_tenant_cusip": "DK002360",
        "location_display": "El Paso, TX",
        "location_city": "El Paso",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 31.7587,
        "lon": -106.4869,
        "news_queries": ["El Paso Texas datacenter", "Meta datacenter El Paso", "Project Sopaipilla datacenter"],
        "twitter_queries": ["El Paso datacenter", "Meta Texas datacenter"],
        # Financial
        "tranche_size_mm": 12274,
        "coupon": "6.480%",
        "maturity": "2048 (~22yr)",
        "wal_yr": 16,
        "ratings": "NR/A+",
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": 175,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Meta",
        "counterparty_rating": "Aa3/AA/AA",
        "lease_tenor_yr": 20,
        "ultimate_tenant": "Meta",
        "ultimate_tenant_tenor_yr": 20,
        "guarantor": "Meta / Parent",
        "guarantee_trigger": "RVG since Inception",
        # Contingencies
        "power_contingency": "Perform under utility contract",
        "cost_overrun": "Pass through to Meta Parent",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 1400,
        "critical_it_mw": 960,
        "critical_it_pct": 69,
        "pue": 1.458,
        "completion_date": "2028-12-01",
        # Economics
        "lease_agreement_mm": 26800,
        "contract_tenure_yr": 20,
        "initial_per_mw_yr_mm": 1.396,
        "construction_cost_mm": 14340,
        "per_mw_critical_mm": 14.94,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 9.34,
        "annual_revenue_mm": 1340,
        "noi_mm": 1340,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.92,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort through 2048",
        "amort_pct_tranche": "Full amort",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "Optional at par + make-whole",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "9.2x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Not Disclosed",
        "epc_market_cap": "N/A",
        "subcontractors": "N/A",
        "surety": "Meta Parent Gty (overruns >105%)",
    },
    {
        "id": "glxy_helios",
        "name": "GLXY Helios Phase II",
        "cusip": "BBG023X2YYQ0",
        "underlying_tenant_cusip": "21873SAG3",
        "location_display": "Afton, Dickens Co., TX",
        "location_city": "Afton",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 33.7665,
        "lon": -100.7710,
        "news_queries": ["Afton Texas datacenter", "Galaxy Digital Helios datacenter", "CoreWeave Dickens County Texas datacenter"],
        "twitter_queries": ["Galaxy Helios datacenter", "CoreWeave Texas datacenter"],
        # Financial
        "tranche_size_mm": 3094,
        "coupon": "9.875%",
        "maturity": "2031 (~5yr)",
        "wal_yr": 5,
        "ratings": "~BB",
        "price": 99.759,
        "ytw_pct": 9.937,
        "stw_bps": 556.58,
        "ytc_pct": 12.259,
        "stc_bps": 796.94,
        "call_protection": "Jul-2028",
        "call_price": 103.75,
        "market_cap": "Private",
        "spread_for_underlying_bps": 823.94,
        "spread_to_underlying_bps": -267.35,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "TBD",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "Galaxy",
        "guarantee_trigger": None,
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": "GLXY Parent",
        "construction_delay": "180 days",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 400,
        "critical_it_mw": 260,
        "critical_it_pct": 65,
        "pue": 1.538,
        "completion_date": "2027-12-27",
        # Economics
        "lease_agreement_mm": 9000,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 2.308,
        "construction_cost_mm": 3575,
        "per_mw_critical_mm": 13.75,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 16.78,
        "annual_revenue_mm": 600,
        "noi_mm": 540,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 17.45,
        "pct_principal_at_maturity": "~96%",
        "amort_schedule": None,
        "amort_pct_tranche": "4%",
        "amort_yr1": "I/O",
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "5.7x",
        "debt_noi_maturity": "2.2x",
        # Construction
        "epc": "HITT",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "Parent Uncapped Gty",
    },
    {
        "id": "sbe_milam",
        "name": "SBE Milam",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Milam Co., TX",
        "location_city": "Cameron",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 30.7880,
        "lon": -96.9700,
        "news_queries": ["Milam County Texas datacenter", "OpenAI Stargate Milam County Texas", "SBE Milam datacenter"],
        "twitter_queries": ["OpenAI Texas datacenter", "Milam County datacenter"],
        # Financial
        "tranche_size_mm": None,
        "coupon": None,
        "maturity": "~5yr",
        "wal_yr": 5,
        "ratings": "~BB",
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": "May-2028",
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Orion DC I (OpenAI sub)",
        "counterparty_rating": "NR",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "OpenAI",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Energy Global (SBE Parent)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": None,
        "construction_delay": "None",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 446,
        "critical_it_mw": 308,
        "critical_it_pct": 69,
        "pue": 1.448,
        "completion_date": "2028-01-28",
        # Economics
        "lease_agreement_mm": 13300,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 2.882,
        "construction_cost_mm": 6500,
        "per_mw_critical_mm": 21.10,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": 13.66,
        "annual_revenue_mm": 887.8,
        "noi_mm": 887.8,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": None,
        "pct_principal_at_maturity": None,
        "amort_schedule": "Sculpted to 1.45x DSCR after initial refi",
        "amort_pct_tranche": None,
        "amort_yr1": "I/O",
        "amort_as_pct_noi": None,
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": None,
        "debt_noi_maturity": None,
        # Construction
        "epc": "DPR and Sundt JV",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": None,
    },
    {
        "id": "qts_magnolia",
        "name": "QTS Magnolia TLB",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Richmond VA / Phoenix + Glendale AZ / New Albany OH / DFW TX (12 assets)",
        "location_city": "Richmond",
        "location_state": "Multiple",
        "location_state_abbr": "US",
        "lat": 37.5407,
        "lon": -77.4360,
        "news_queries": ["QTS data center portfolio", "QTS Magnolia financing", "QTS Blackstone hyperscale datacenter"],
        "twitter_queries": ["QTS datacenter", "QTS Blackstone datacenter"],
        # Financial
        "tranche_size_mm": 1000,
        "coupon": "5.750%",
        "maturity": "2033 (~7yr)",
        "wal_yr": 7,
        "ratings": "ND",
        "price": 100.0,
        "ytw_pct": 5.750,
        "stw_bps": 137.85,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": "Soft call",
        "call_price": 101.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "MSFT / Meta / Oracle",
        "counterparty_rating": "AA+ (WA)",
        "lease_tenor_yr": "15.2 / 28.9",
        "ultimate_tenant": "Microsoft / Meta / Oracle",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "N/A - stabilized",
        "guarantee_trigger": "N/A",
        # Contingencies
        "power_contingency": "100% pass-through",
        "cost_overrun": "N/A - operating",
        "construction_delay": "N/A",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Stabilized Hyperscale (12 assets)",
        "total_campus_mw": None,
        "critical_it_mw": 494,
        "critical_it_pct": None,
        "pue": None,
        "completion_date": None,
        # Economics
        "lease_agreement_mm": 9272,
        "contract_tenure_yr": 15.2,
        "initial_per_mw_yr_mm": 1.235,
        "construction_cost_mm": None,
        "per_mw_critical_mm": None,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": None,
        "annual_revenue_mm": 610,
        "noi_mm": 613,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 7.74,
        "pct_principal_at_maturity": "100%",
        "amort_schedule": "1.20x DSCR-sized + sweep",
        "amort_pct_tranche": "1.5%/yr",
        "amort_yr1": "$15mm",
        "amort_as_pct_noi": "2.4%",
        "ecf_sweep": "Yes - waterfall sweep",
        "ecf_sweep_annual": "$125mm",
        "debt_noi_yr1": "1.6x",
        "debt_noi_maturity": "1.6x",
        # Construction
        "epc": "N/A - operating",
        "epc_market_cap": "N/A",
        "subcontractors": "N/A",
        "surety": "N/A",
    },
    {
        "id": "zenith",
        "name": "Zenith",
        "cusip": "BBG024BDSMG2",
        "underlying_tenant_cusip": None,
        "location_display": "Central Oklahoma",
        "location_city": None,
        "location_state": "Oklahoma",
        "location_state_abbr": "OK",
        "lat": 35.4676,
        "lon": -97.5164,
        "news_queries": ["Fluidstack Oklahoma datacenter", "Zenith Next Frontier Oklahoma data center", "Jane Street datacenter Oklahoma"],
        "twitter_queries": ["Fluidstack Oklahoma datacenter", "Jane Street datacenter"],
        # Financial
        "tranche_size_mm": 2350,
        "coupon": None,
        "maturity": "2031 (~5yr)",
        "wal_yr": 5,
        "ratings": "~BB",
        "price": 96.356,
        "ytw_pct": 9.808,
        "stw_bps": 542.60,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Jane St",
        "counterparty_rating": "Ba1/BB/BBB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Jane St",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Subsidiary Gtors + Tenant support",
        "guarantee_trigger": "From signing (parent lease gty)",
        # Contingencies
        "power_contingency": "Pass-through",
        "cost_overrun": "GC above Final GMP; Tenant downside",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey AI/HPC",
        "total_campus_mw": 200,
        "critical_it_mw": 149,
        "critical_it_pct": 75,
        "pue": 1.342,
        "completion_date": "2028-11-28",
        # Economics
        "lease_agreement_mm": 5111,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.805,
        "construction_cost_mm": 2133,
        "per_mw_critical_mm": 14.32,
        "at_cost_to_debt": "0.9x",
        "yield_on_cost_pct": 15.24,
        "annual_revenue_mm": 269,
        "noi_mm": 325,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 13.83,
        "pct_principal_at_maturity": "88%",
        "amort_schedule": "DSCR-sculpted (1.20x)",
        "amort_pct_tranche": "2.9%/yr",
        "amort_yr1": "$68mm",
        "amort_as_pct_noi": "21%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "8.7x",
        "debt_noi_maturity": "6.3x",
        # Construction
        "epc": "Alston (GC) / SHIPP (Substation)",
        "epc_market_cap": "Private",
        "subcontractors": "Gensler (AE)",
        "surety": "GMP w/ LDs; subs bonded",
    },
    {
        "id": "digital_drive",
        "name": "Digital Drive",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Chesterfield Co., VA",
        "location_city": "Chesterfield",
        "location_state": "Virginia",
        "location_state_abbr": "VA",
        "lat": 37.3771,
        "lon": -77.5836,
        "news_queries": ["Chesterfield County Virginia datacenter", "CoreWeave Chesterfield Virginia data center", "Digital Drive Blue Owl datacenter"],
        "twitter_queries": ["CoreWeave Chesterfield Virginia datacenter", "Blue Owl CoreWeave datacenter"],
        # Financial
        "tranche_size_mm": 1085,
        "coupon": "8.500%",
        "maturity": "2031 (~5yr)",
        "wal_yr": 5,
        "ratings": "~BB-",
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "CoreWeave, Inc.",
        "counterparty_rating": "B+/Ba3/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "IG Hyperscaler (via CRWV GPU SPV)",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Blue Owl funds (uncapped completion gty)",
        "guarantee_trigger": "Springing or full CRWV gty, by SPV rating",
        # Contingencies
        "power_contingency": "ESA executed (300MW); substation complete",
        "cost_overrun": "DPR (mismanagement); CW otherwise",
        "construction_delay": "No termination for delay/convenience",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey AI/HPC",
        "total_campus_mw": 100,
        "critical_it_mw": 76,
        "critical_it_pct": 76,
        "pue": 1.316,
        "completion_date": "2028-08-01",
        # Economics
        "lease_agreement_mm": 2940,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.855,
        "construction_cost_mm": 1379,
        "per_mw_critical_mm": 18.14,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 12.98,
        "annual_revenue_mm": 141,
        "noi_mm": 179,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 16.50,
        "pct_principal_at_maturity": "93%",
        "amort_schedule": "2.00% + 0.60% annual step-ups",
        "amort_pct_tranche": "2%/yr",
        "amort_yr1": "$21.7mm",
        "amort_as_pct_noi": "12%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "7.7x",
        "debt_noi_maturity": "5.7x",
        # Construction
        "epc": "DPR Construction (GC)",
        "epc_market_cap": "Private",
        "subcontractors": "Gensler (A&E); subs 50% bought out",
        "surety": "GMP $1,064mm w/ LDs & incentives",
    },
    {
        "id": "novva_lv_reno",
        "name": "Novva LV1 + Reno",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "N. Las Vegas + Reno, NV",
        "location_city": "North Las Vegas",
        "location_state": "Nevada",
        "location_state_abbr": "NV",
        "lat": 36.1989,
        "lon": -115.1175,
        "news_queries": ["Novva data center Las Vegas", "Novva Reno data center", "CoreWeave eBay Novva datacenter Nevada", "CIM Novva data center"],
        "twitter_queries": ["Novva data center Nevada", "CoreWeave eBay Novva datacenter"],
        # Financial
        "tranche_size_mm": 800,
        "coupon": "8.000%",
        "maturity": "2031 (~5yr)",
        "wal_yr": 5,
        "ratings": "~BB",
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "CoreWeave / eBay",
        "counterparty_rating": "B+/Ba3/BB- (CRWV); BBB+/Baa1 (eBay)",
        "lease_tenor_yr": 11,
        "ultimate_tenant": "CoreWeave / eBay (direct)",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "NOVVA Holdings LLC (completion gty)",
        "guarantee_trigger": "None - parent gty to FCD only",
        # Contingencies
        "power_contingency": "NVE ESAs executed; substations built",
        "cost_overrun": "Contractors (NTE/GMP); Novva gty",
        "construction_delay": "No term. <180d; then phase-only",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey (Modified Gross)",
        "total_campus_mw": 175,
        "critical_it_mw": 97.5,
        "critical_it_pct": 56,
        "pue": 1.795,
        "completion_date": "2028-06-01",
        # Economics
        "lease_agreement_mm": 1950,
        "contract_tenure_yr": 11.2,
        "initial_per_mw_yr_mm": 1.475,
        "construction_cost_mm": 1454,
        "per_mw_critical_mm": 14.91,
        "at_cost_to_debt": "1.8x",
        "yield_on_cost_pct": 8.18,
        "annual_revenue_mm": 143.8,
        "noi_mm": 119,
        "noi_margin_pct": 81,
        "implied_debt_yield_pct": 14.88,
        "pct_principal_at_maturity": "78%",
        "amort_schedule": "Semiannual from 1H'28, ~1.10x DSCR",
        "amort_pct_tranche": "3.2%/yr",
        "amort_yr1": "$25.5mm",
        "amort_as_pct_noi": "21%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "6.9x",
        "debt_noi_maturity": "5.3x",
        # Construction
        "epc": "Salas O'Brien (LV1) / Martin Harris (Reno)",
        "epc_market_cap": "Private",
        "subcontractors": "Cache Valley, Cerris, Vanguard; Briggs, RHP",
        "surety": "LV1 NTE/fixed-price w/ LDs; Reno GMP",
    },
    {
        "id": "pure_dc",
        "name": "Pure DC (EUR)",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "FLAP-D / Nordics / Abu Dhabi / Jakarta",
        "location_city": None,
        "location_state": "Multiple",
        "location_state_abbr": "EU",
        "lat": 50.1109,
        "lon": 8.6821,
        "news_queries": ["Pure Data Centres Group", "Pure DC data center Oaktree", "Pure DC hyperscale Europe financing"],
        "twitter_queries": ["Pure DC data center", "Pure Data Centres Oaktree"],
        # Financial
        "tranche_size_mm": 1000,
        "coupon": "3mE + TBD",
        "maturity": "2031 (~5yr)",
        "wal_yr": 5,
        "ratings": "NR",
        "price": 100.0,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": "NC2",
        "call_price": 103.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "US Hyperscalers (6 sites)",
        "counterparty_rating": "~90% AA+ or better",
        "lease_tenor_yr": 14.5,
        "ultimate_tenant": "US Hyperscalers",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "Oaktree overrun gty (~10% of capex)",
        "guarantee_trigger": "None",
        # Contingencies
        "power_contingency": "Secured (all sites)",
        "cost_overrun": "Contingency 3-7% + Oaktree gty",
        "construction_delay": "N/A",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale (leased)",
        "total_campus_mw": 498.25,
        "critical_it_mw": 399,
        "critical_it_pct": 80,
        "pue": 1.249,
        "completion_date": "2032-12-31",
        # Economics
        "lease_agreement_mm": 6500,
        "contract_tenure_yr": 14.5,
        "initial_per_mw_yr_mm": 1.862,
        "construction_cost_mm": 6497,
        "per_mw_critical_mm": 16.28,
        "at_cost_to_debt": "6.5x",
        "yield_on_cost_pct": 9.80,
        "annual_revenue_mm": 743,
        "noi_mm": 637,
        "noi_margin_pct": 86,
        "implied_debt_yield_pct": 10.23,
        "pct_principal_at_maturity": "100%",
        "amort_schedule": "Bullet",
        "amort_pct_tranche": None,
        "amort_yr1": None,
        "amort_as_pct_noi": None,
        "ecf_sweep": "Optional 10% p.a. @ call px",
        "ecf_sweep_annual": "Up to 10% p.a. (optional)",
        "debt_noi_yr1": "1.6x",
        "debt_noi_maturity": "1.6x",
        # Construction
        "epc": "Tier-1 GCs (not named)",
        "epc_market_cap": "Private / ND",
        "subcontractors": "Fixed-price EPC; conting. 3-7%",
        "surety": "Oaktree gty ~10% of capex",
    },
]


# Reorder: IG bonds first, then by tier
_ORDER = [
    "beignet", "sopaipilla", "hut_google", "hut_beacon_point", "related_bx", "vantage", "stack_nm",
    "qts", "qts_magnolia", "meridian",
    "tract", "tract_d", "cifr_black_pearl", "cifr_stingray", "wulf", "flashc",
    "cifr_barber_lake", "apld_pf2", "apld", "apld_eln4", "voltag", "yondr_nova",
    "edged_compute", "core_scientific", "glxy_helios", "sbe_softbank", "sbe_milam", "polar_dc", "prime_dc",
    "zenith", "digital_drive", "novva_lv_reno", "pure_dc",
]
_BOND_MAP_RAW = {b["id"]: b for b in BONDS}
BONDS = [_BOND_MAP_RAW[k] for k in _ORDER if k in _BOND_MAP_RAW]
BOND_MAP = {b["id"]: b for b in BONDS}

