BONDS = [
    {
        "id": "beignet",
        "name": "Project Beignet",
        "cusip": "076912AA2",
        "underlying_tenant_cusip": "30303M8X3",
        "location_display": "Richland Parish, LA",
        "location_city": "Rayville",
        "location_state": "Louisiana",
        "location_state_abbr": "LA",
        "lat": 32.4827,
        "lon": -91.7540,
        "news_queries": ["Richland Parish Louisiana datacenter", "Meta datacenter Louisiana", "Project Beignet datacenter"],
        "twitter_queries": ["Richland Parish datacenter", "Meta Louisiana datacenter"],
        # Financial
        "tranche_size_mm": 27294,
        "coupon": "6.581% (T+225)",
        "maturity": "2049 (~24yr)",
        "wal_yr": 17,
        "ratings": "NR/A+",
        "price": 103.644,
        "ytw_pct": 6.256,
        "stw_bps": 161.81,
        "ytc_pct": 6.256,
        "stc_bps": 161.81,
        "call_protection": "NCL",
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": 101.47,
        "spread_to_underlying_bps": 60.34,
        # Lease
        "lease_counterparty": "Meta",
        "counterparty_rating": "Aa3/AA/AA",
        "lease_tenor_yr": 24,
        "ultimate_tenant": "Meta",
        "ultimate_tenant_tenor_yr": 24,
        "guarantor": "Meta / Parent",
        "guarantee_trigger": "RVG since Inception",
        # Contingencies
        "power_contingency": "Perform under Entergy contract",
        "cost_overrun": "Pass through to Meta Parent",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 2100,
        "critical_it_mw": 1704,
        "critical_it_pct": 81,
        "pue": 1.232,
        "completion_date": "2029-06-01",
        # Economics
        "lease_agreement_mm": 28800,
        "contract_tenure_yr": 24,
        "initial_per_mw_yr_mm": 1.6,
        "construction_cost_mm": 28800,
        "per_mw_critical_mm": 16.9,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 9.47,
        "annual_revenue_mm": 2760,
        "noi_mm": 2760,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.11,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort through 2049",
        "amort_pct_tranche": "Full amort",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "Optional at par + make-whole",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "9.9x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Not Disclosed",
        "epc_market_cap": "N/A",
        "subcontractors": "N/A",
        "surety": "Meta Parent Gty (overruns >105%)",
    },
    {
        "id": "related_bx",
        "name": "Related/BX",
        "cusip": "74941YAA0",
        "underlying_tenant_cusip": "68389XDZ5",
        "location_display": "Washtenaw Co., MI",
        "location_city": "Ann Arbor",
        "location_state": "Michigan",
        "location_state_abbr": "MI",
        "lat": 42.2808,
        "lon": -83.7430,
        "news_queries": ["Washtenaw County Michigan datacenter", "Related Companies Oracle datacenter Michigan", "Ann Arbor datacenter"],
        "twitter_queries": ["Washtenaw Michigan datacenter", "Related BX Oracle datacenter"],
        "sub_tranches": [
            {
                "id": "related_bx_sd",
                "name": "Related/BX — Short-Duration Bond",
                "cusip": None,
                "underlying_tenant_cusip": "68389XDX0",
                "tranche_size_mm": 13849,
                "coupon": "6.250%",
                "maturity": "~6yr",
                "wal_yr": 6,
                "ratings": "NR/BBB/BBB-",
                "price": 99.0,
                "ytw_pct": 6.45,
                "stw_bps": 270.46,
                "ytc_pct": 7.59,
                "stc_bps": 409.40,
                "call_protection": 3,
                "call_price": 103.125,
                "ecf_sweep": "Cash Sweep",
                "ecf_sweep_annual": "N/A",
                "debt_noi_yr1": "10.0x",
                "debt_noi_maturity": "TBD",
                "amort_pct_tranche": "Full amort in lease",
                "amort_yr1": "I/O during term",
                "pct_principal_at_maturity": "N/A",
            },
            {
                "id": "related_bx_bank",
                "name": "Related/BX — Bank Financing",
                "cusip": None,
                "underlying_tenant_cusip": "68389XDZ5",
                "tranche_size_mm": 13849,
                "coupon": "S+300",
                "maturity": "4+1+1",
                "wal_yr": 4,
                "ratings": "NR/BBB/BBB-",
                "price": 100.0,
                "ytw_pct": None,
                "stw_bps": None,
                "ecf_sweep": "Cash Sweep",
                "ecf_sweep_annual": "Sculpted",
                "amort_pct_tranche": "Full amort in lease",
                "amort_yr1": "I/O during term",
            },
        ],
        # Financial (main tranche)
        "tranche_size_mm": 14000,
        "coupon": "7.500%",
        "maturity": "3/30/2045",
        "wal_yr": 14.25,
        "ratings": "NR/BBB/BBB-",
        "price": 100.119,
        "ytw_pct": 7.512,
        "stw_bps": 353.99,
        "ytc_pct": 7.443,
        "stc_bps": 369.26,
        "call_protection": 3,
        "call_price": 100.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": 189.5,
        "spread_to_underlying_bps": 164.49,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Related",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 1400,
        "critical_it_mw": 974,
        "critical_it_pct": 70,
        "pue": 1.22,
        "completion_date": "2028-03-31",
        # Economics
        "lease_agreement_mm": 16293,
        "contract_tenure_yr": 19.5,
        "initial_per_mw_yr_mm": 1.4,
        "construction_cost_mm": 16293,
        "per_mw_critical_mm": 16.7,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.75,
        "annual_revenue_mm": 1383,
        "noi_mm": 1383,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 9.88,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Full amort in lease",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during term",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "10.0x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Walbridge (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "kW Mission Critical / SMC",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "vantage",
        "name": "Vantage",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Shackelford Co., TX + WI",
        "location_city": "Albany",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.7295,
        "lon": -99.2978,
        "news_queries": ["Shackelford County Texas datacenter Vantage", "Vantage Data Centers Oracle Texas", "Albany Texas datacenter"],
        "twitter_queries": ["Vantage datacenter Texas", "Vantage Data Centers Oracle"],
        # Financial
        "tranche_size_mm": 38000,
        "coupon": "S+250",
        "maturity": "4+1+1",
        "wal_yr": None,
        "ratings": "BBB (KBRA)",
        "price": 100.0,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Vantage",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 2260,
        "critical_it_mw": 2260,
        "critical_it_pct": 100,
        "pue": 1.22,
        "completion_date": "2028-09-01",
        # Economics
        "lease_agreement_mm": 44706,
        "contract_tenure_yr": 15.7,
        "initial_per_mw_yr_mm": 1.7,
        "construction_cost_mm": 44706,
        "per_mw_critical_mm": 19.8,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.5,
        "annual_revenue_mm": 3800,
        "noi_mm": 3800,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.0,
        "pct_principal_at_maturity": "98% (w/ extensions)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "100% Post-Maturity / 1.75yr pre-lease exp",
        "debt_noi_yr1": "10.0x",
        "debt_noi_maturity": "10.0x",
        # Construction
        "epc": "Kiewit (TX) / Turner, Whiting-Turner, Weitz, McCarthy (WI)",
        "epc_market_cap": "Private",
        "subcontractors": "Various Subs",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "stack_nm",
        "name": "Stack NM",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Santa Teresa, NM",
        "location_city": "Santa Teresa",
        "location_state": "New Mexico",
        "location_state_abbr": "NM",
        "lat": 31.8690,
        "lon": -106.6940,
        "news_queries": ["Santa Teresa New Mexico datacenter", "Dona Ana County New Mexico datacenter Stack", "Stack Infrastructure New Mexico Oracle"],
        "twitter_queries": ["Santa Teresa NM datacenter", "Stack Infrastructure New Mexico datacenter"],
        # Financial
        "tranche_size_mm": 18009,
        "coupon": "S+250",
        "maturity": "4+1+1",
        "wal_yr": None,
        "ratings": "BBB (KBRA)",
        "price": None,
        "ytw_pct": None,
        "stw_bps": None,
        "ytc_pct": None,
        "stc_bps": None,
        "call_protection": None,
        "call_price": None,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 18,
        "ultimate_tenant": "OpenAI / Meta et al",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Stack",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 1725,
        "critical_it_mw": 1278,
        "critical_it_pct": 74,
        "pue": 1.35,
        "completion_date": "2028-08-31",
        # Economics
        "lease_agreement_mm": 21187,
        "contract_tenure_yr": 17.9,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 21187,
        "per_mw_critical_mm": 16.6,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 8.5,
        "annual_revenue_mm": 1857,
        "noi_mm": 1857,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 10.31,
        "pct_principal_at_maturity": "98% (w/ extensions)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "Sculpted",
        "debt_noi_yr1": "9.7x",
        "debt_noi_maturity": "9.7x",
        # Construction
        "epc": "Clayco-Kiewit JV (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "SMC (MEP Engineer)",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "tract",
        "name": "Tract",
        "cusip": "78488XAA2",
        "underlying_tenant_cusip": None,
        "location_display": "Storey County, NV",
        "location_city": "Virginia City",
        "location_state": "Nevada",
        "location_state_abbr": "NV",
        "lat": 39.3963,
        "lon": -119.6500,
        "news_queries": ["Storey County Nevada datacenter NVIDIA", "Tract NVIDIA datacenter Nevada", "Virginia City Nevada datacenter"],
        "twitter_queries": ["Storey County Nevada datacenter", "NVIDIA datacenter Nevada Tract"],
        # Financial
        "tranche_size_mm": 3800,
        "coupon": "5.875%",
        "maturity": "3/1/2031",
        "wal_yr": None,
        "ratings": "Ba1/BB",
        "price": 99.852,
        "ytw_pct": 5.898,
        "stw_bps": 200.97,
        "ytc_pct": 7.411,
        "stc_bps": 396.08,
        "call_protection": 2,
        "call_price": 102.938,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "NVIDIA",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 16,
        "ultimate_tenant": "NVIDIA",
        "ultimate_tenant_tenor_yr": 16,
        "guarantor": "Fleet",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "2031",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 200,
        "critical_it_mw": 200,
        "critical_it_pct": 100,
        "pue": None,
        "completion_date": "2029-08-15",
        # Economics
        "lease_agreement_mm": 7989,
        "contract_tenure_yr": 16.4,
        "initial_per_mw_yr_mm": 1.85,
        "construction_cost_mm": 4400,
        "per_mw_critical_mm": 22.0,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 9.5,
        "annual_revenue_mm": 370,
        "noi_mm": 370,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 9.74,
        "pct_principal_at_maturity": "93.1%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "3%",
        "amort_yr1": "$109mm",
        "amort_as_pct_noi": "29%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "9.9x",
        "debt_noi_maturity": "7.8x",
        # Construction
        "epc": "Clark Construction Group (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "Phase X / PASE (Private)",
        "surety": "Fleet I Completion Gty (GMP + Perf Bond TBD)",
    },
    {
        "id": "cifr_black_pearl",
        "name": "CIFR — Black Pearl",
        "cusip": "09216NAA8",
        "underlying_tenant_cusip": None,
        "location_display": "Wink, TX",
        "location_city": "Wink",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 31.7513,
        "lon": -103.1588,
        "news_queries": ["Wink Texas CIFR datacenter Amazon", "Cipher Mining Black Pearl datacenter", "Winkler County Texas datacenter"],
        "twitter_queries": ["Wink Texas CIFR datacenter", "Cipher Mining Amazon datacenter Texas"],
        # Financial
        "tranche_size_mm": 2000,
        "coupon": "6.125%",
        "maturity": "2/15/2031",
        "wal_yr": None,
        "ratings": "Ba2/—",
        "price": 102.177,
        "ytw_pct": 5.485,
        "stw_bps": 164.13,
        "ytc_pct": 6.440,
        "stc_bps": 299.00,
        "call_protection": 2,
        "call_price": 103.063,
        "market_cap": "$7.19B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Amazon",
        "counterparty_rating": "A1/AA",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Amazon",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "CIFR Parent ($6B mkt cap)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "150 days",
        "counterparty_debt_yield_pct": 4.27,
        "issuer_spread_to_cp_bps": 223.0,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 300,
        "critical_it_mw": 216,
        "critical_it_pct": 72,
        "pue": 1.4,
        "completion_date": "2027-01-28",
        # Economics
        "lease_agreement_mm": 5480,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.4,
        "construction_cost_mm": 2050,
        "per_mw_critical_mm": 9.5,
        "at_cost_to_debt": "1.0x",
        "yield_on_cost_pct": 14.74,
        "annual_revenue_mm": 300,
        "noi_mm": 298,
        "noi_margin_pct": 99,
        "implied_debt_yield_pct": 14.9,
        "pct_principal_at_maturity": "72.5%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "7%",
        "amort_yr1": "$140mm",
        "amort_as_pct_noi": "47%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "6.7x",
        "debt_noi_maturity": "3.x",
        # Construction
        "epc": "Quanta Services",
        "epc_market_cap": "$71.8B",
        "subcontractors": "Undisclosed",
        "surety": "$2,052mm parent gty",
    },
    {
        "id": "wulf",
        "name": "WULF",
        "cusip": "982911AA7",
        "underlying_tenant_cusip": None,
        "location_display": "Lake Mariner, NY",
        "location_city": "Somerset",
        "location_state": "New York",
        "location_state_abbr": "NY",
        "lat": 43.3445,
        "lon": -78.5076,
        "news_queries": ["Lake Mariner TeraWulf datacenter Google", "TeraWulf New York datacenter Fluidstack", "Somerset Niagara County New York datacenter"],
        "twitter_queries": ["TeraWulf Lake Mariner datacenter", "WULF Google datacenter New York"],
        # Financial
        "tranche_size_mm": 3200,
        "coupon": "7.750%",
        "maturity": "10/15/2030",
        "wal_yr": None,
        "ratings": "Ba2/BB",
        "price": 105.976,
        "ytw_pct": 5.839,
        "stw_bps": 201.54,
        "ytc_pct": 6.033,
        "stc_bps": 258.27,
        "call_protection": 2,
        "call_price": 103.875,
        "market_cap": "$8.25B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 10,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Terawulf Parent ($6B mkt cap)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "N/A",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 224.7,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 522.5,
        "critical_it_mw": 426,
        "critical_it_pct": 82,
        "pue": 1.2,
        "completion_date": "2026-12-26",
        # Economics
        "lease_agreement_mm": 6714,
        "contract_tenure_yr": 10,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 3659,
        "per_mw_critical_mm": 8.6,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 17.44,
        "annual_revenue_mm": 653,
        "noi_mm": 565,
        "noi_margin_pct": 87,
        "implied_debt_yield_pct": 17.66,
        "pct_principal_at_maturity": "60.1%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "8.78%",
        "amort_yr1": "$281mm",
        "amort_as_pct_noi": "50%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$60mm+",
        "debt_noi_yr1": "5.0x",
        "debt_noi_maturity": "2.6x",
        # Construction
        "epc": "Beowulf (Self Managed)",
        "epc_market_cap": "Various Small",
        "subcontractors": "Various Small",
        "surety": "$3,157mm parent gty",
    },
    {
        "id": "flashc",
        "name": "FLASHC",
        "cusip": "33853QAA9",
        "underlying_tenant_cusip": None,
        "location_display": "Abernathy, TX",
        "location_city": "Abernathy",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 33.8343,
        "lon": -101.8318,
        "news_queries": ["Abernathy Texas datacenter Fluidstack Google", "FLASHC datacenter Texas Hypertec", "Hale County Texas datacenter"],
        "twitter_queries": ["Abernathy Texas datacenter", "Fluidstack Google Texas datacenter FLASHC"],
        # Financial
        "tranche_size_mm": 1300,
        "coupon": "7.250%",
        "maturity": "12/31/2030",
        "wal_yr": None,
        "ratings": "Ba3/—",
        "price": 101.86,
        "ytw_pct": 6.671,
        "stw_bps": 283.52,
        "ytc_pct": 8.071,
        "stc_bps": 462.08,
        "call_protection": 2,
        "call_price": 103.625,
        "market_cap": "$8.25B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Fluidstack/TeraWulf JV $100mm",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "N/A (Life of lease)",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 315.2,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 240,
        "critical_it_mw": 168,
        "critical_it_pct": 70,
        "pue": 1.4,
        "completion_date": "2026-09-26",
        # Economics
        "lease_agreement_mm": 9500,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.331,
        "construction_cost_mm": 1354,
        "per_mw_critical_mm": 8.1,
        "at_cost_to_debt": "1.0x",
        "yield_on_cost_pct": 16.43,
        "annual_revenue_mm": 264,
        "noi_mm": 183,
        "noi_margin_pct": 69,
        "implied_debt_yield_pct": 14.08,
        "pct_principal_at_maturity": "65.0%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "5.77%",
        "amort_yr1": "$75mm",
        "amort_as_pct_noi": "41%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$16mm",
        "debt_noi_yr1": "7.0x",
        "debt_noi_maturity": "3.6x",
        # Construction
        "epc": "Hypertec (Private)",
        "epc_market_cap": "Mastec / Conti",
        "subcontractors": "Mastec / Conti",
        "surety": "$1,200mm Hypertec",
    },
    {
        "id": "cifr_barber_lake",
        "name": "CIFR (Barber Lake)",
        "cusip": "17253NAA5",
        "underlying_tenant_cusip": None,
        "location_display": "Colorado City, TX",
        "location_city": "Colorado City",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.3893,
        "lon": -100.8773,
        "news_queries": ["Colorado City Texas CIFR datacenter Google", "Mitchell County Texas datacenter Cipher Mining", "Colorado City Texas Barber Lake datacenter"],
        "twitter_queries": ["Colorado City Texas CIFR datacenter", "Cipher Mining Barber Lake Google"],
        # Financial
        "tranche_size_mm": 1733,
        "coupon": "7.125%",
        "maturity": "11/15/2030",
        "wal_yr": None,
        "ratings": "Ba3/—",
        "price": 104.418,
        "ytw_pct": 6.006,
        "stw_bps": 211.75,
        "ytc_pct": 6.319,
        "stc_bps": 286.94,
        "call_protection": 2,
        "call_price": 103.563,
        "market_cap": "$7.19B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 10,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "CIFR Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "180 days (Life of lease)",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": 228.9,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 300,
        "critical_it_mw": 207,
        "critical_it_pct": 69,
        "pue": 1.4,
        "completion_date": "2026-09-30",
        # Economics
        "lease_agreement_mm": 3834,
        "contract_tenure_yr": 10,
        "initial_per_mw_yr_mm": 1.6,
        "construction_cost_mm": 1214,
        "per_mw_critical_mm": 10.7,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 14.95,
        "annual_revenue_mm": 333,
        "noi_mm": 288,
        "noi_margin_pct": 86,
        "implied_debt_yield_pct": 16.62,
        "pct_principal_at_maturity": "61.1%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "8.77%",
        "amort_yr1": "$152mm",
        "amort_as_pct_noi": "53%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$10mm+",
        "debt_noi_yr1": "5.5x",
        "debt_noi_maturity": "3.2x",
        # Construction
        "epc": "Quanta Services",
        "epc_market_cap": "$71.8B",
        "subcontractors": "Undisclosed",
        "surety": "$1,763mm parent gty",
    },
    {
        "id": "apld_pf2",
        "name": "APLD PF-2 (PFORGE)",
        "cusip": "03772CAA1",
        "underlying_tenant_cusip": "68389XDX0",
        "location_display": "Harwood, ND",
        "location_city": "Harwood",
        "location_state": "North Dakota",
        "location_state_abbr": "ND",
        "lat": 46.9757,
        "lon": -97.1845,
        "news_queries": ["Harwood North Dakota APLD datacenter Oracle", "Applied Digital Harwood ND datacenter", "Cass County North Dakota datacenter"],
        "twitter_queries": ["Harwood North Dakota datacenter", "APLD Applied Digital Oracle datacenter ND"],
        # Financial
        "tranche_size_mm": 2100,
        "coupon": "6.875%",
        "maturity": "3/15/2031",
        "wal_yr": None,
        "ratings": "BB",
        "price": 101.225,
        "ytw_pct": 6.408,
        "stw_bps": 252.95,
        "ytc_pct": 7.839,
        "stc_bps": 433.88,
        "call_protection": 2,
        "call_price": 103.44,
        "market_cap": "Private",
        "spread_for_underlying_bps": 144.91,
        "spread_to_underlying_bps": 108.04,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "TBD",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Applied Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "150 days",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 230,
        "critical_it_mw": 200,
        "critical_it_pct": 100,
        "pue": 1.15,
        "completion_date": "2027-04-01",
        # Economics
        "lease_agreement_mm": 9000,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.344,
        "construction_cost_mm": 2687,
        "per_mw_critical_mm": 13.4,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 10.03,
        "annual_revenue_mm": 250,
        "noi_mm": 250,
        "noi_margin_pct": 88,
        "implied_debt_yield_pct": 11.90,
        "pct_principal_at_maturity": "82.2%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "4.25%",
        "amort_yr1": "$61mm",
        "amort_as_pct_noi": "24.4%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "10.5x",
        "debt_noi_maturity": "6.7x",
        # Construction
        "epc": "Adolfson & Peterson (Private)",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "APLD Parent Completion Gty",
    },
    {
        "id": "apld",
        "name": "APLD",
        "cusip": "00202DAA5",
        "underlying_tenant_cusip": None,
        "location_display": "Ellendale, ND",
        "location_city": "Ellendale",
        "location_state": "North Dakota",
        "location_state_abbr": "ND",
        "lat": 46.0041,
        "lon": -98.5290,
        "news_queries": ["Ellendale North Dakota APLD datacenter CoreWeave", "Applied Digital Ellendale ND datacenter", "Dickey County North Dakota datacenter"],
        "twitter_queries": ["Ellendale North Dakota datacenter", "APLD Applied Digital CoreWeave datacenter"],
        # Financial
        "tranche_size_mm": 2350,
        "coupon": "9.250%",
        "maturity": "12/15/2030",
        "wal_yr": None,
        "ratings": "/BB-",
        "price": 107.657,
        "ytw_pct": 6.956,
        "stw_bps": 320.89,
        "ytc_pct": 6.956,
        "stc_bps": 350.64,
        "call_protection": 2,
        "call_price": 104.625,
        "market_cap": "$9.92B",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "META",
        "ultimate_tenant_tenor_yr": 5,
        "guarantor": "Applied Parent",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": "180 days",
        "counterparty_debt_yield_pct": 9.70,
        "issuer_spread_to_cp_bps": -163.7,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 295,
        "critical_it_mw": 250,
        "critical_it_pct": 85,
        "pue": 1.2,
        "completion_date": "2026-06-26",
        # Economics
        "lease_agreement_mm": 6764,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 3100,
        "per_mw_critical_mm": 12.4,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 12.10,
        "annual_revenue_mm": 368,
        "noi_mm": 330,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 14.04,
        "pct_principal_at_maturity": "74.6%",
        "amort_schedule": "Yes",
        "amort_pct_tranche": "7.74%",
        "amort_yr1": "$182mm",
        "amort_as_pct_noi": "55%",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "$60mm",
        "debt_noi_yr1": "6.6x",
        "debt_noi_maturity": "~0x (near full amort)",
        # Construction
        "epc": "McGough (Private)",
        "epc_market_cap": "Undisclosed",
        "subcontractors": "Undisclosed",
        "surety": "$3,099mm parent gty",
    },
    {
        "id": "voltag",
        "name": "VOLTAG",
        "cusip": "92874BAA3",
        "underlying_tenant_cusip": None,
        "location_display": "Shackelford Co., TX",
        "location_city": "Albany",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 32.7295,
        "lon": -99.2978,
        "news_queries": ["Shackelford County Texas VOLTAG datacenter Oracle Vantage", "Vantage Data Centers Oracle Texas Albany", "Albany Texas datacenter Shackelford"],
        "twitter_queries": ["Shackelford Texas VOLTAG datacenter", "Vantage Oracle Texas datacenter"],
        # Financial
        "tranche_size_mm": 2000,
        "coupon": "7.375%",
        "maturity": "11/1/2030",
        "wal_yr": None,
        "ratings": "B3/B+/BB-",
        "price": 103.827,
        "ytw_pct": 6.156,
        "stw_bps": 233.02,
        "ytc_pct": 7.017,
        "stc_bps": 356.66,
        "call_protection": 2,
        "call_price": 103.688,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "Oracle",
        "counterparty_rating": "Baa2/BBB/BBB",
        "lease_tenor_yr": None,
        "ultimate_tenant": "OpenAI",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "ORCL (Vantage)",
        "guarantee_trigger": None,
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": None,
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": None,
        "critical_it_mw": None,
        "critical_it_pct": None,
        "pue": None,
        "completion_date": None,
        # Economics
        "lease_agreement_mm": None,
        "contract_tenure_yr": None,
        "initial_per_mw_yr_mm": None,
        "construction_cost_mm": None,
        "per_mw_critical_mm": None,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": None,
        "annual_revenue_mm": None,
        "noi_mm": None,
        "noi_margin_pct": None,
        "implied_debt_yield_pct": None,
        "pct_principal_at_maturity": None,
        "amort_schedule": "Yes",
        "amort_pct_tranche": None,
        "amort_yr1": None,
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": None,
        "debt_noi_yr1": None,
        "debt_noi_maturity": None,
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "qts",
        "name": "QTS",
        "cusip": "74751AAA1",
        "underlying_tenant_cusip": "594918BS2",
        "location_display": "Fayetteville, GA",
        "location_city": "Fayetteville",
        "location_state": "Georgia",
        "location_state_abbr": "GA",
        "lat": 33.4490,
        "lon": -84.4549,
        "news_queries": ["Fayetteville Georgia QTS datacenter Microsoft", "QTS Realty Trust Microsoft Georgia datacenter", "Fayette County Georgia datacenter"],
        "twitter_queries": ["Fayetteville Georgia QTS datacenter", "QTS Microsoft datacenter Georgia"],
        # Financial
        "tranche_size_mm": 4600,
        "coupon": "7.375%",
        "maturity": "4/15/2036",
        "wal_yr": None,
        "ratings": "Baa2",
        "price": 99.245,
        "ytw_pct": 5.801,
        "stw_bps": 149.68,
        "ytc_pct": 5.805,
        "stc_bps": 235.46,
        "call_protection": 10,
        "call_price": 100.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": None,
        "spread_to_underlying_bps": None,
        # Lease
        "lease_counterparty": "MSFT",
        "counterparty_rating": "Aaa/AAA",
        "lease_tenor_yr": 20,
        "ultimate_tenant": "MSFT",
        "ultimate_tenant_tenor_yr": None,
        "guarantor": "QTS",
        "guarantee_trigger": None,
        # Contingencies
        "power_contingency": None,
        "cost_overrun": None,
        "construction_delay": None,
        "counterparty_debt_yield_pct": 4.5,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": None,
        "critical_it_mw": None,
        "critical_it_pct": None,
        "pue": None,
        "completion_date": None,
        # Economics
        "lease_agreement_mm": None,
        "contract_tenure_yr": None,
        "initial_per_mw_yr_mm": None,
        "construction_cost_mm": None,
        "per_mw_critical_mm": None,
        "at_cost_to_debt": None,
        "yield_on_cost_pct": None,
        "annual_revenue_mm": None,
        "noi_mm": None,
        "noi_margin_pct": None,
        "implied_debt_yield_pct": None,
        "pct_principal_at_maturity": None,
        "amort_schedule": "Yes",
        "amort_pct_tranche": None,
        "amort_yr1": None,
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": None,
        "debt_noi_yr1": None,
        "debt_noi_maturity": None,
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "meridian",
        "name": "Meridian",
        "cusip": "58990CAA1",
        "underlying_tenant_cusip": "02079KBK2",
        "location_display": "Sullivan Co., IN",
        "location_city": "New Lebanon",
        "location_state": "Indiana",
        "location_state_abbr": "IN",
        "lat": 39.1667,
        "lon": -87.4167,
        "news_queries": ["New Lebanon Indiana datacenter Google", "Sullivan County Indiana datacenter", "Meridian datacenter Fluidstack Indiana", "Next Frontier Capital datacenter Indiana"],
        "twitter_queries": ["Sullivan County Indiana datacenter", "Meridian datacenter Google Indiana"],
        # Financial
        "tranche_size_mm": 5700,
        "coupon": "6.500%",
        "maturity": "4/30/2031",
        "wal_yr": None,
        "ratings": "Ba1/BB",
        "price": 100.314,
        "ytw_pct": 6.1509,
        "stw_bps": 229.45,
        "ytc_pct": 7.5245,
        "stc_bps": 377.45,
        "call_protection": 2,
        "call_price": 103.125,
        "market_cap": "Private",
        "spread_for_underlying_bps": 71.71,
        "spread_to_underlying_bps": 157.73,
        # Lease
        "lease_counterparty": "Fluidstack/Google",
        "counterparty_rating": "Private/NR",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Fluidstack + Next Frontier ($100mm each)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "Pass through to Tenant",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": 4.09,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 581,
        "critical_it_mw": 430,
        "critical_it_pct": 74,
        "pue": 1.35,
        "completion_date": "2028-02-28",
        # Economics
        "lease_agreement_mm": 12108,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.514,
        "construction_cost_mm": 6250,
        "per_mw_critical_mm": 14.5,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 10.42,
        "annual_revenue_mm": 651,
        "noi_mm": 651,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 11.42,
        "pct_principal_at_maturity": "84.1%",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Sculpted to 1.25x DSCR",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "50%",
        "ecf_sweep_annual": "Sculpted (1.25x DSCR)",
        "debt_noi_yr1": "8.8x",
        "debt_noi_maturity": "7.4x",
        # Construction
        "epc": "ARCO DB Companies, Inc.",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "edged_compute",
        "name": "Edged Compute",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Aurora, IL + Atlanta, GA",
        "location_city": "Aurora",
        "location_state": "Illinois",
        "location_state_abbr": "IL",
        "lat": 41.7606,
        "lon": -88.3201,
        "news_queries": ["Aurora Illinois datacenter CoreWeave Edged", "Edged Compute datacenter CoreWeave Alibaba", "Edged Energy datacenter Illinois Atlanta", "Aurora Illinois datacenter Koch"],
        "twitter_queries": ["Edged Compute datacenter", "Aurora Illinois CoreWeave datacenter"],
        # Financial
        "tranche_size_mm": 1300,
        "coupon": "7.500%",
        "maturity": "4/30/2031",
        "wal_yr": 4.75,
        "ratings": "~BB",
        "price": 100.0,
        "ytw_pct": 7.4959,
        "stw_bps": 358.45,
        "ytc_pct": 9.2764,
        "stc_bps": 549.10,
        "call_protection": 2,
        "call_price": 103.75,
        "market_cap": "Private",
        "spread_for_underlying_bps": 608.86,
        "spread_to_underlying_bps": -250.41,
        # Lease
        "lease_counterparty": "CoreWeave / Alibaba",
        "counterparty_rating": "B1/B/BB- (CW) / NR (Alibaba)",
        "lease_tenor_yr": 16,
        "ultimate_tenant": "CoreWeave / Alibaba",
        "ultimate_tenant_tenor_yr": 16,
        "guarantor": "Edged US Parent (uncapped, Koch)",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "NNN (Chicago) / Landlord (Atlanta)",
        "cost_overrun": "BABA: Landlord bears overruns; CRWV: rent adjusts for cost increases",
        "construction_delay": "270 days CRWV / None ATL",
        "counterparty_debt_yield_pct": 10.0,
        "issuer_spread_to_cp_bps": -250.41,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 142,
        "critical_it_mw": 114,
        "critical_it_pct": 80,
        "pue": 1.25,
        "completion_date": "2027-12-31",
        # Economics
        "lease_agreement_mm": 3590,
        "contract_tenure_yr": 16,
        "initial_per_mw_yr_mm": 1.737,
        "construction_cost_mm": 1721,
        "per_mw_critical_mm": 15.1,
        "at_cost_to_debt": "1.3x",
        "yield_on_cost_pct": 11.50,
        "annual_revenue_mm": 198,
        "noi_mm": 179,
        "noi_margin_pct": 90,
        "implied_debt_yield_pct": 13.77,
        "pct_principal_at_maturity": "90%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "5.08%",
        "amort_yr1": "I/O",
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "7.3x",
        "debt_noi_maturity": "6.5x",
        # Construction
        "epc": "FCL Builders (Chicago) / Brasfield & Gorrie (Atlanta)",
        "epc_market_cap": "Private",
        "subcontractors": "Various",
        "surety": "GMP w/ Parent Uncapped Gty",
    },
    {
        "id": "core_scientific",
        "name": "Core Scientific",
        "cusip": None,
        "underlying_tenant_cusip": None,
        "location_display": "Multiple (TX/NC/OK/GA)",
        "location_city": "Denton",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 33.2148,
        "lon": -97.1331,
        "news_queries": ["Core Scientific CoreWeave HPC datacenter", "CORZ datacenter hosting AI", "Core Scientific datacenter lease CoreWeave"],
        "twitter_queries": ["Core Scientific CoreWeave datacenter", "CORZ HPC datacenter"],
        # Financial
        "tranche_size_mm": 3300,
        "coupon": "7.500%",
        "maturity": "4/30/2031",
        "wal_yr": 4.25,
        "ratings": "~BB",
        "price": 100.0,
        "ytw_pct": 7.4954,
        "stw_bps": 358.40,
        "ytc_pct": 9.2764,
        "stc_bps": 549.10,
        "call_protection": 2,
        "call_price": 103.75,
        "market_cap": "Public (CORZ)",
        "spread_for_underlying_bps": 608.86,
        "spread_to_underlying_bps": -250.46,
        # Lease
        "lease_counterparty": "CoreWeave",
        "counterparty_rating": "B1/B/BB-",
        "lease_tenor_yr": 12,
        "ultimate_tenant": "OAI / Meta / MSFT",
        "ultimate_tenant_tenor_yr": 12,
        "guarantor": "CoreWeave",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": "CoreWeave",
        "construction_delay": "None",
        "counterparty_debt_yield_pct": 10.0,
        "issuer_spread_to_cp_bps": -250.46,
        # Campus
        "product": "Powered Shell",
        "total_campus_mw": 900,
        "critical_it_mw": 590,
        "critical_it_pct": 66,
        "pue": 1.53,
        "completion_date": "2027-06-30",
        # Economics
        "lease_agreement_mm": 9155,
        "contract_tenure_yr": 12,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 5500,
        "per_mw_critical_mm": 9.32,
        "at_cost_to_debt": "1.7x",
        "yield_on_cost_pct": 16.09,
        "annual_revenue_mm": 763,
        "noi_mm": 602,
        "noi_margin_pct": 79,
        "implied_debt_yield_pct": 18.24,
        "pct_principal_at_maturity": "73.8%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "11.5%",
        "amort_yr1": "$0",
        "amort_as_pct_noi": None,
        "ecf_sweep": None,
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "5.5x",
        "debt_noi_maturity": "1.9x",
        # Construction
        "epc": None,
        "epc_market_cap": None,
        "subcontractors": None,
        "surety": None,
    },
    {
        "id": "hut_google",
        "name": "HUT / Google",
        "cusip": None,
        "underlying_tenant_cusip": "02079KBK2",
        "location_display": "River Bend, LA",
        "location_city": "River Bend",
        "location_state": "Louisiana",
        "location_state_abbr": "LA",
        "lat": 30.7500,
        "lon": -91.3330,
        "news_queries": ["River Bend Louisiana HUT Google datacenter", "HUT 8 Google datacenter Louisiana", "St Francisville Louisiana datacenter"],
        "twitter_queries": ["River Bend Louisiana datacenter Google", "HUT Google datacenter Louisiana"],
        # Financial
        "tranche_size_mm": 3248,
        "coupon": "6.200%",
        "maturity": "12/31/2042",
        "wal_yr": 12,
        "ratings": "Baa2/BBB-",
        "price": 100.0,
        "ytw_pct": 6.199,
        "stw_bps": 176.69,
        "ytc_pct": 6.199,
        "stc_bps": 176.69,
        "call_protection": "NCL",
        "call_price": "N/A",
        "market_cap": "Private",
        "spread_for_underlying_bps": 36.5,
        "spread_to_underlying_bps": 140.19,
        # Lease
        "lease_counterparty": "Fluidstack / Google",
        "counterparty_rating": "Aa2/AA+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Google/Anthropic",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Hut/Jacobs/Google",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None, tenant responsibility",
        "cost_overrun": "GMP with Jacobs",
        "construction_delay": "No Termination Rights",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 330,
        "critical_it_mw": 245,
        "critical_it_pct": 74,
        "pue": 1.347,
        "completion_date": "2027-10-01",
        # Economics
        "lease_agreement_mm": 6982,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.853,
        "construction_cost_mm": 3468,
        "per_mw_critical_mm": 14.16,
        "at_cost_to_debt": "1.1x",
        "yield_on_cost_pct": 13.09,
        "annual_revenue_mm": 454,
        "noi_mm": 454,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 13.98,
        "pct_principal_at_maturity": "0% (Full Amort)",
        "amort_schedule": "Sculpted",
        "amort_pct_tranche": "Full amort in lease",
        "amort_yr1": "I/O during construction",
        "amort_as_pct_noi": "N/A",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "None",
        "debt_noi_yr1": "7.2x",
        "debt_noi_maturity": "N/A",
        # Construction
        "epc": "Jacobs",
        "epc_market_cap": "$15B",
        "subcontractors": "Vertiv",
        "surety": "GMP + Completion Gty",
    },
    {
        "id": "sbe_softbank",
        "name": "SBE / Softbank",
        "cusip": None,
        "underlying_tenant_cusip": "XS3112542272",
        "location_display": "Austin, TX",
        "location_city": "Austin",
        "location_state": "Texas",
        "location_state_abbr": "TX",
        "lat": 30.2672,
        "lon": -97.7431,
        "news_queries": ["Austin Texas SBE Softbank datacenter", "Softbank Austin Texas datacenter", "Travis County Texas datacenter Softbank"],
        "twitter_queries": ["Austin Texas Softbank datacenter", "SBE Softbank datacenter Texas"],
        # Financial
        "tranche_size_mm": 1000,
        "coupon": "8.000%",
        "maturity": "4/30/2031",
        "wal_yr": 4.75,
        "ratings": "~BB",
        "price": 100.0,
        "ytw_pct": 7.995,
        "stw_bps": 391.29,
        "ytc_pct": 9.886,
        "stc_bps": 593.32,
        "call_protection": 2,
        "call_price": 104.0,
        "market_cap": "Private",
        "spread_for_underlying_bps": 400.0,
        "spread_to_underlying_bps": -8.71,
        # Lease
        "lease_counterparty": "Softbank",
        "counterparty_rating": "Ba2/BB+",
        "lease_tenor_yr": 15,
        "ultimate_tenant": "Softbank",
        "ultimate_tenant_tenor_yr": 15,
        "guarantor": "Softbank",
        "guarantee_trigger": "Substantial Completion",
        # Contingencies
        "power_contingency": "None",
        "cost_overrun": "Softbank",
        "construction_delay": "None",
        "counterparty_debt_yield_pct": None,
        "issuer_spread_to_cp_bps": None,
        # Campus
        "product": "Turnkey Hyperscale",
        "total_campus_mw": 70,
        "critical_it_mw": 50,
        "critical_it_pct": 71,
        "pue": 1.4,
        "completion_date": "2027-06-30",
        # Economics
        "lease_agreement_mm": 2400,
        "contract_tenure_yr": 15,
        "initial_per_mw_yr_mm": 1.5,
        "construction_cost_mm": 1181,
        "per_mw_critical_mm": 23.62,
        "at_cost_to_debt": "1.2x",
        "yield_on_cost_pct": 11.62,
        "annual_revenue_mm": 167,
        "noi_mm": 167,
        "noi_margin_pct": 100,
        "implied_debt_yield_pct": 16.67,
        "pct_principal_at_maturity": "92.5%",
        "amort_schedule": "Semi-annual sculpted",
        "amort_pct_tranche": "0%",
        "amort_yr1": "$0mm",
        "amort_as_pct_noi": "0%",
        "ecf_sweep": "None",
        "ecf_sweep_annual": "N/A",
        "debt_noi_yr1": "6.0x",
        "debt_noi_maturity": "5.5x",
        # Construction
        "epc": "Turner",
        "epc_market_cap": "Private",
        "subcontractors": None,
        "surety": None,
    },
]


# Reorder: IG bonds first, then by tier
_ORDER = [
    "beignet", "hut_google", "related_bx", "vantage", "stack_nm", "qts", "meridian",
    "tract", "cifr_black_pearl", "wulf", "flashc",
    "cifr_barber_lake", "apld_pf2", "apld", "voltag",
    "edged_compute", "core_scientific", "sbe_softbank",
]
_BOND_MAP_RAW = {b["id"]: b for b in BONDS}
BONDS = [_BOND_MAP_RAW[k] for k in _ORDER if k in _BOND_MAP_RAW]
BOND_MAP = {b["id"]: b for b in BONDS}

